(()=>{"use strict";
const canvas=document.getElementById("game-canvas"),ctx=canvas.getContext("2d"),W=390,H=844,dpr=Math.max(1,Math.min(devicePixelRatio||1,2));
const source={bg:"assets/game/meadow-base.png",tree:"assets/game/tree.png",logs:"assets/game/logs.png",rocks:"assets/game/rocks.png",grass:"assets/game/grass.png",berries:"assets/game/berries.png",campfire:"assets/game/campfire.png",workbench:"assets/game/workbench.png",lamp:"assets/game/lamp.png",garden:"assets/game/garden.png",base:"assets/unity/chick-base.png",scout:"assets/unity/chick-scout.png",builder:"assets/unity/chick-builder.png"},assets={};
const rewardNames={wood:"나무",stone:"돌",sprout:"새싹",berry:"열매"};
const state={clock:0,intro:true,energy:12,maxEnergy:12,resources:{wood:2,stone:0,sprout:1,berry:0},cleared:0,plays:0,happiness:0,buildMode:null,rewarded:false,selectedChick:"base",effects:[],particles:[]};
const entities=[
 {id:"tree-a",type:"tree",x:70,y:360,size:118,hp:3,maxHp:3,reward:{wood:3}},
 {id:"rocks-a",type:"rocks",x:315,y:390,size:93,hp:3,maxHp:3,reward:{stone:3}},
 {id:"logs-a",type:"logs",x:91,y:535,size:92,hp:2,maxHp:2,reward:{wood:2}},
 {id:"grass-a",type:"grass",x:306,y:544,size:82,hp:1,maxHp:1,reward:{sprout:2}},
 {id:"berries-a",type:"berries",x:274,y:686,size:91,hp:2,maxHp:2,reward:{berry:3}},
 {id:"grass-b",type:"grass",x:65,y:694,size:76,hp:1,maxHp:1,reward:{sprout:2}}
];
const chicks=[
 {id:"base",name:"삐약이",asset:"base",x:172,y:463,tx:232,ty:500,size:68,phase:0,status:"새 마을이 궁금해서 두리번거리고 있어요."},
 {id:"scout",name:"상어삐약",asset:"scout",x:236,y:604,tx:140,ty:624,size:66,phase:2.2,status:"개울 건너편을 탐험하고 돌아왔어요."}
];
const facilities=[];
const recipes={
 campfire:{name:"포근한 모닥불",asset:"campfire",desc:"쉬면서 기운을 채워요.",cost:{wood:3,stone:2},size:94},
 workbench:{name:"나무 작업대",asset:"workbench",desc:"가끔 나무를 만들어요.",cost:{wood:4,stone:2},size:100},
 garden:{name:"작은 텃밭",asset:"garden",desc:"열매와 새싹을 길러요.",cost:{wood:2,sprout:2},size:106},
 lamp:{name:"마을 가로등",asset:"lamp",desc:"마을의 행복을 밝혀요.",cost:{wood:2,stone:1},size:91}
};
const load=()=>Promise.all(Object.entries(source).map(([key,src])=>new Promise(resolve=>{const img=new Image();img.onload=()=>{assets[key]=img;resolve()};img.onerror=()=>resolve();img.src=src})));
function resize(){const rect=canvas.getBoundingClientRect();canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);ctx.setTransform(rect.width/W*dpr,0,0,rect.height/H*dpr,0,0);render()}
function drawContain(img,x,y,w,h=w,alpha=1){if(!img)return;const scale=Math.min(w/img.width,h/img.height),dw=img.width*scale,dh=img.height*scale;ctx.save();ctx.globalAlpha=alpha;ctx.drawImage(img,x+(w-dw)/2,y+(h-dh)/2,dw,dh);ctx.restore()}
function drawBackground(){if(!assets.bg){ctx.fillStyle="#dff2a8";ctx.fillRect(0,0,W,H);return}const scale=Math.max(W/assets.bg.width,H/assets.bg.height),dw=assets.bg.width*scale,dh=assets.bg.height*scale;ctx.drawImage(assets.bg,(W-dw)/2,(H-dh)/2,dw,dh)}
function shadowEllipse(x,y,rx,ry,alpha=.18){ctx.save();ctx.fillStyle=`rgba(48,73,42,${alpha})`;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill();ctx.restore()}
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function drawEntity(e){if(e.hp<=0&&e.fade<=0)return;const shake=e.shake>0?Math.sin(state.clock*55)*4:0,alpha=e.fade===undefined?1:Math.max(0,e.fade/.38);shadowEllipse(e.x,e.y+e.size*.28,e.size*.29,e.size*.1,.14*alpha);drawContain(assets[e.type],e.x-e.size/2+shake,e.y-e.size*.68,e.size,e.size,alpha);if(e.hp>0&&e.hp<e.maxHp){const w=43,x=e.x-w/2,y=e.y-e.size*.49;ctx.fillStyle="#fff9e6";roundRect(x-2,y-2,w+4,9,5);ctx.fill();ctx.fillStyle="#e8b9a7";roundRect(x,y,w,5,3);ctx.fill();ctx.fillStyle="#62aa50";roundRect(x,y,w*(e.hp/e.maxHp),5,3);ctx.fill()}}
function drawFacility(f){shadowEllipse(f.x,f.y+f.size*.25,f.size*.28,f.size*.1);drawContain(assets[f.type],f.x-f.size/2,f.y-f.size*.66,f.size,f.size);if(f.cooldown>state.clock){const remain=Math.ceil(f.cooldown-state.clock);ctx.fillStyle="#fffdf2e8";roundRect(f.x-20,f.y-f.size*.5,40,18,9);ctx.fill();ctx.fillStyle="#596258";ctx.font="900 9px sans-serif";ctx.textAlign="center";ctx.fillText(`${remain}초`,f.x,f.y-f.size*.5+12)}}
function drawChick(c){const bob=Math.sin(state.clock*3+c.phase)*2.4;shadowEllipse(c.x,c.y+25,c.size*.25,c.size*.08,.16);ctx.save();ctx.shadowColor="#3f52373b";ctx.shadowBlur=6;ctx.shadowOffsetY=3;drawContain(assets[c.asset],c.x-c.size/2,c.y-c.size*.62+bob,c.size,c.size);ctx.restore();if(c.id==="builder"&&state.clock-c.arrivedAt<5){ctx.fillStyle="#fffdf2";roundRect(c.x-31,c.y-c.size*.68,62,20,10);ctx.fill();ctx.fillStyle="#4c6545";ctx.font="900 9px sans-serif";ctx.textAlign="center";ctx.fillText("새 친구!",c.x,c.y-c.size*.68+13)}}
function drawBuildGhost(){if(!state.buildMode)return;const r=recipes[state.buildMode],x=state.pointer?.x||196,y=state.pointer?.y||500,valid=validPlacement(x,y);ctx.save();ctx.globalAlpha=.68;shadowEllipse(x,y+r.size*.25,r.size*.3,r.size*.12,.16);drawContain(assets[r.asset],x-r.size/2,y-r.size*.66,r.size,r.size);ctx.strokeStyle=valid?"#4b9c42":"#d85343";ctx.lineWidth=3;ctx.setLineDash([7,5]);ctx.beginPath();ctx.ellipse(x,y+16,48,25,0,0,Math.PI*2);ctx.stroke();ctx.restore()}
function drawEffects(){for(const e of state.effects){const t=e.life/e.max;ctx.save();ctx.globalAlpha=Math.min(1,t*2);ctx.fillStyle=e.color||"#fff";ctx.strokeStyle="#493f2f";ctx.lineWidth=3;ctx.font="900 14px sans-serif";ctx.textAlign="center";ctx.strokeText(e.text,e.x,e.y);ctx.fillText(e.text,e.x,e.y);ctx.restore()}for(const p of state.particles){ctx.save();ctx.globalAlpha=Math.max(0,p.life/.65);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill();ctx.restore()}}
function render(){ctx.clearRect(0,0,W,H);drawBackground();const layers=[];entities.filter(e=>e.hp>0||e.fade>0).forEach(e=>layers.push({y:e.y,draw:()=>drawEntity(e)}));facilities.forEach(f=>layers.push({y:f.y,draw:()=>drawFacility(f)}));chicks.forEach(c=>layers.push({y:c.y,draw:()=>drawChick(c)}));layers.sort((a,b)=>a.y-b.y).forEach(l=>l.draw());drawBuildGhost();drawEffects()}
function update(dt){state.clock+=dt;for(const e of entities){e.shake=Math.max(0,(e.shake||0)-dt);if(e.hp<=0)e.fade=Math.max(0,(e.fade??.38)-dt)}for(const e of state.effects){e.life-=dt;e.y-=22*dt}state.effects=state.effects.filter(e=>e.life>0);for(const p of state.particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=55*dt}state.particles=state.particles.filter(p=>p.life>0);for(const c of chicks){const dx=c.tx-c.x,dy=c.ty-c.y,dist=Math.hypot(dx,dy);if(dist<5){const points=[[115,440],[205,420],[287,484],[112,610],[225,642],[300,580]],next=points[(Math.floor(state.clock/2)+Math.round(c.phase*3))%points.length];c.tx=next[0];c.ty=next[1]}else{const speed=c.id==="builder"?13:10;c.x+=dx/dist*speed*dt;c.y+=dy/dist*speed*dt}}}
function canvasPoint(event){const r=canvas.getBoundingClientRect();return{x:(event.clientX-r.left)/r.width*W,y:(event.clientY-r.top)/r.height*H}}
function hitEntity(p){return entities.filter(e=>e.hp>0).reverse().find(e=>Math.hypot(p.x-e.x,p.y-(e.y-e.size*.15))<e.size*.43)}
function hitChick(p){return [...chicks].reverse().find(c=>Math.hypot(p.x-c.x,p.y-(c.y-c.size*.18))<c.size*.48)}
function hitFacility(p){return [...facilities].reverse().find(f=>Math.hypot(p.x-f.x,p.y-(f.y-f.size*.15))<f.size*.42)}
function hitWorld(p){const hits=[];for(const e of entities.filter(e=>e.hp>0))if(Math.hypot(p.x-e.x,p.y-(e.y-e.size*.15))<e.size*.43)hits.push({kind:"entity",item:e,y:e.y});for(const f of facilities)if(Math.hypot(p.x-f.x,p.y-(f.y-f.size*.15))<f.size*.42)hits.push({kind:"facility",item:f,y:f.y});for(const c of chicks)if(Math.hypot(p.x-c.x,p.y-(c.y-c.size*.18))<c.size*.48)hits.push({kind:"chick",item:c,y:c.y});return hits.sort((a,b)=>b.y-a.y)[0]}
function validPlacement(x,y){if(y<330||y>720||x<48||x>342)return false;return ![...entities.filter(e=>e.hp>0),...facilities,...chicks].some(o=>Math.hypot(x-o.x,y-o.y)<68)}
function burst(x,y,color="#f2c650"){for(let i=0;i<9;i++){const angle=Math.PI*2*i/9+i*.17;state.particles.push({x,y:y-14,vx:Math.cos(angle)*(24+4*i),vy:Math.sin(angle)*(24+4*i)-28,r:2+i%3,life:.65,color})}}
function floatText(x,y,text,color="#fff4a8"){state.effects.push({x,y,text,color,life:.85,max:.85})}
function gather(e){if(state.energy<=0){toast("기운이 없어요. 병아리와 함께 쉬어주세요.");return}state.energy--;e.hp--;e.shake=.22;burst(e.x,e.y-e.size*.15);floatText(e.x,e.y-e.size*.55,"톡!");if(e.hp<=0){Object.entries(e.reward).forEach(([key,value])=>{state.resources[key]+=value;floatText(e.x,e.y-e.size*.36,`+${value} ${rewardNames[key]}`,"#fff4a8")});state.cleared++;burst(e.x,e.y-e.size*.12,"#8ecb65");toast(`${Object.entries(e.reward).map(([k,v])=>`${rewardNames[k]} ${v}개`).join(", ")}를 모았어요`)}syncUI();checkQuest()}
function placeFacility(x,y){if(!validPlacement(x,y)){toast("다른 물건과 겹치지 않는 빈 잔디를 골라주세요.");return}const type=state.buildMode,r=recipes[type];if(!canAfford(r.cost)){cancelBuild();toast("재료가 부족해요.");return}Object.entries(r.cost).forEach(([key,value])=>state.resources[key]-=value);facilities.push({id:`${type}-${facilities.length+1}`,type,x,y,size:r.size,cooldown:0});state.buildMode=null;state.pointer=null;document.getElementById("mode-banner").hidden=true;burst(x,y,"#ffd45c");floatText(x,y-r.size*.55,"완성!","#fff4a8");toast(`${r.name}을 완성했어요`);syncUI();checkQuest()}
function useFacility(f){const r=recipes[f.type];if(f.cooldown>state.clock){toast(`${r.name}은 잠시 뒤에 다시 이용할 수 있어요.`);return}if(f.type==="campfire"){state.energy=Math.min(state.maxEnergy,state.energy+3);speak("모닥불이 따뜻해요. 기운을 3 회복했어요!");f.cooldown=12}else if(f.type==="garden"){state.resources.berry++;state.resources.sprout++;speak("텃밭에서 열매와 새싹을 수확했어요!");f.cooldown=15}else if(f.type==="workbench"){state.resources.wood++;speak("작업대에서 쓸 만한 나무를 다듬었어요!");f.cooldown=12}else{state.happiness+=2;speak("불빛을 보고 병아리들이 행복해해요!");f.cooldown=10}burst(f.x,f.y-f.size*.2);syncUI()}
function openFriend(chick=chicks[0]){state.selectedChick=chick.id;document.getElementById("friend-name").textContent=chick.name;document.getElementById("friend-image").src=source[chick.asset];document.getElementById("friend-status").textContent=chick.status;openSheet("friend-sheet")}
function friendAction(action){const chick=chicks.find(c=>c.id===state.selectedChick)||chicks[0];if(action==="play"){state.plays++;state.happiness+=2;speak(`${chick.name}: 같이 뛰어놀아서 신나요!`);burst(chick.x,chick.y-24,"#ff8d84")}else if(action==="feed"){if(state.resources.berry<1){toast("열매가 없어요. 열매 덤불을 정리해 보세요.");return}state.resources.berry--;state.happiness+=3;speak(`${chick.name}: 새콤달콤해서 맛있어요!`)}else{state.energy=Math.min(state.maxEnergy,state.energy+2);speak(`${chick.name}와 잠깐 쉬며 기운을 회복했어요.`)}closeSheets();syncUI();checkQuest()}
function canAfford(cost){return Object.entries(cost).every(([key,value])=>state.resources[key]>=value)}
function costText(cost){return Object.entries(cost).map(([k,v])=>`<span>${rewardNames[k]} ${v}</span>`).join("")}
function renderRecipes(){document.getElementById("recipe-list").innerHTML=Object.entries(recipes).map(([key,r])=>{const affordable=canAfford(r.cost),placed=facilities.some(f=>f.type===key);return `<button class="recipe ${affordable?"affordable":"locked"} ${placed?"placed":""}" data-recipe="${key}"><img src="${source[r.asset]}" alt=""><strong>${r.name}</strong><small>${r.desc}</small><span class="recipe-cost">${costText(r.cost)}</span></button>`}).join("");document.querySelectorAll("[data-recipe]").forEach(button=>button.onclick=()=>selectRecipe(button.dataset.recipe))}
function selectRecipe(type){const r=recipes[type];if(!canAfford(r.cost)){toast("재료가 부족해요. 마을의 자원을 먼저 모아주세요.");return}closeSheets();state.buildMode=type;state.pointer={x:196,y:520};document.getElementById("mode-title").textContent=`${r.name} 놓기`;document.getElementById("mode-banner").hidden=false;toast("빈 잔디를 눌러 설치하세요.")}
function cancelBuild(){state.buildMode=null;state.pointer=null;document.getElementById("mode-banner").hidden=true}
function questData(){return[{name:"빈터 세 곳 정리",desc:"나무, 돌, 풀을 눌러 정리해요.",current:Math.min(state.cleared,3),goal:3},{name:"포근한 모닥불 짓기",desc:"짓기 메뉴에서 모닥불을 골라요.",current:facilities.some(f=>f.type==="campfire")?1:0,goal:1},{name:"병아리와 두 번 놀기",desc:"병아리를 누르고 같이 놀아요.",current:Math.min(state.plays,2),goal:2}]}
function renderQuests(){const quests=questData();document.getElementById("quest-list").innerHTML=quests.map((q,i)=>{const done=q.current>=q.goal;return `<article class="quest-row ${done?"done":""}"><i>${done?"✓":i+1}</i><span><strong>${q.name}</strong><small>${q.desc}</small></span><b>${q.current}/${q.goal}</b></article>`}).join("");const done=quests.filter(q=>q.current>=q.goal).length;document.getElementById("quest-total").textContent=`${done}/3`;document.getElementById("quest-summary").textContent=done===3?"오늘의 의뢰 완료!":quests.find(q=>q.current<q.goal).name}
function checkQuest(){renderQuests();if(!state.rewarded&&questData().every(q=>q.current>=q.goal)){state.rewarded=true;state.happiness+=20;chicks.push({id:"builder",name:"뚝딱삐약",asset:"builder",x:202,y:286,tx:205,ty:430,size:68,phase:4.4,status:"마을 시설을 만드는 일이 가장 즐거워요.",arrivedAt:state.clock});toast("의뢰 완료! 새 주민 뚝딱삐약이 찾아왔어요.");burst(202,274,"#ffd85b")}}
function renderBag(){const items=[{k:"wood",icon:"◆"},{k:"stone",icon:"●"},{k:"sprout",icon:"♣"},{k:"berry",icon:"●"}];document.getElementById("bag-grid").innerHTML=items.map(i=>`<article class="bag-item"><b class="${i.k}">${i.icon}</b><strong>${state.resources[i.k]}</strong><small>${rewardNames[i.k]}</small></article>`).join("")}
function syncUI(){for(const key of Object.keys(state.resources))document.getElementById(`${key}-count`).textContent=state.resources[key];document.getElementById("energy-count").textContent=state.energy;renderQuests();renderBag();renderRecipes()}
function openSheet(id){closeSheets();if(id==="build-sheet")renderRecipes();if(id==="quest-sheet")renderQuests();if(id==="bag-sheet")renderBag();document.getElementById(id).hidden=false}
function closeSheets(){document.querySelectorAll(".bottom-sheet").forEach(sheet=>sheet.hidden=true)}
function toast(message){const el=document.getElementById("toast");el.textContent=message;el.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove("show"),1900)}
function speak(message){const el=document.getElementById("speech-bubble");el.textContent=message;el.classList.add("show");clearTimeout(speak.timer);speak.timer=setTimeout(()=>el.classList.remove("show"),1900)}
function onCanvas(event){if(state.intro)return;const p=canvasPoint(event);if(state.buildMode){placeFacility(p.x,p.y);return}const hit=hitWorld(p);if(!hit){speak("병아리나 반짝이는 자원을 눌러보세요.");return}if(hit.kind==="chick")openFriend(hit.item);else if(hit.kind==="facility")useFacility(hit.item);else gather(hit.item)}
canvas.addEventListener("pointerdown",event=>{event.preventDefault();onCanvas(event)});canvas.addEventListener("pointermove",event=>{if(state.buildMode){state.pointer=canvasPoint(event);render()}});
document.getElementById("start-game").onclick=()=>{state.intro=false;document.getElementById("intro-card").hidden=true;toast("나무, 돌, 풀을 눌러 빈터를 정리해 주세요.")};
document.getElementById("build-button").onclick=()=>openSheet("build-sheet");document.getElementById("bag-button").onclick=()=>openSheet("bag-sheet");document.getElementById("friends-button").onclick=()=>openFriend(chicks[0]);document.getElementById("quest-button").onclick=()=>openSheet("quest-sheet");document.getElementById("cancel-build").onclick=cancelBuild;
document.querySelectorAll("[data-close]").forEach(button=>button.onclick=()=>document.getElementById(button.dataset.close).hidden=true);document.querySelectorAll("[data-friend-action]").forEach(button=>button.onclick=()=>friendAction(button.dataset.friendAction));
document.addEventListener("keydown",event=>{if(event.key==="Escape"){closeSheets();cancelBuild()}});addEventListener("resize",resize);
window.advanceTime=ms=>{for(let i=0,n=Math.max(1,Math.round(ms/(1000/60)));i<n;i++)update(1/60);render()};
window.render_game_to_text=()=>JSON.stringify({coordinate_system:"portrait canvas 390x844; origin top-left",mode:state.intro?"intro":state.buildMode?`placing ${state.buildMode}`:"explore",energy:`${state.energy}/${state.maxEnergy}`,resources:state.resources,happiness:state.happiness,quests:questData(),obstacles:entities.filter(e=>e.hp>0).map(e=>({id:e.id,type:e.type,x:Math.round(e.x),y:Math.round(e.y),hp:`${e.hp}/${e.maxHp}`})),facilities:facilities.map(f=>({type:f.type,x:Math.round(f.x),y:Math.round(f.y),ready:f.cooldown<=state.clock})),chicks:chicks.map(c=>({id:c.id,name:c.name,x:Math.round(c.x),y:Math.round(c.y)})),controls:"Tap obstacles repeatedly to gather. Tap chicks for play/feed/rest. Use 짓기 to choose a facility, then tap empty grass below the river to place it."});
load().then(()=>{resize();syncUI()});let previous=performance.now();function loop(now){update(Math.min(.034,(now-previous)/1000));previous=now;render();requestAnimationFrame(loop)}requestAnimationFrame(loop);
})();
