(()=>{"use strict";
const canvas=document.getElementById("game-canvas"),ctx=canvas.getContext("2d"),W=390,H=844,dpr=Math.max(1,Math.min(devicePixelRatio||1,2));
const source={bg:"assets/game/meadow-base.png",tree:"assets/game/tree.png",logs:"assets/game/logs.png",rocks:"assets/game/rocks.png",grass:"assets/game/grass.png",berries:"assets/game/berries.png",campfire:"assets/game/campfire.png",workbench:"assets/game/workbench.png",lamp:"assets/game/lamp.png",garden:"assets/game/garden.png",picnic:"assets/game/picnic-table.png",arch:"assets/game/flower-arch.png",swing:"assets/game/garden-swing.png",nest:"assets/unity/nest.png",base:"assets/unity/chick-base.png",scout:"assets/unity/chick-scout.png",builder:"assets/unity/chick-builder.png",leaf:"assets/unity/chick-leaf.png",camera:"assets/unity/chick-camera.png",cowboy:"assets/unity/chick-cowboy.png",snow:"assets/unity/chick-snow.png"},assets={};
const rewardNames={wood:"나무",stone:"돌",sprout:"새싹",berry:"열매"};
const state={clock:0,intro:true,day:1,area:"village",energy:12,maxEnergy:12,resources:{wood:2,stone:0,sprout:1,berry:0},cleared:0,forestCleared:0,groveCleared:0,snowCleared:0,plays:0,happiness:0,xp:0,level:1,buildMode:null,visitorPending:false,visitorArrived:false,bridgeRepaired:false,selectedChick:null,effects:[],particles:[],focusedEntity:null};
const reservedTiles=new Set(["1-0","1-3","3-0","3-3","5-0","6-2"]);
const villageTiles=Array.from({length:7},(_,row)=>(row%2?[70,160,250,340]:[115,205,295]).map((x,col)=>({id:`${row}-${col}`,x,y:340+row*55,kind:reservedTiles.has(`${row}-${col}`)?"nature":"build"}))).flat();
const buildTiles=villageTiles.filter(tile=>tile.kind==="build");
const entities=[
 {id:"tree-a",type:"tree",x:70,y:395,size:118,hp:3,maxHp:3,reward:{wood:3}},
 {id:"rocks-a",type:"rocks",x:340,y:395,size:93,hp:3,maxHp:3,reward:{stone:3}},
 {id:"logs-a",type:"logs",x:70,y:505,size:92,hp:2,maxHp:2,reward:{wood:2}},
 {id:"grass-a",type:"grass",x:340,y:505,size:82,hp:1,maxHp:1,reward:{sprout:2}},
 {id:"berries-a",type:"berries",x:295,y:670,size:91,hp:2,maxHp:2,reward:{berry:3}},
 {id:"grass-b",type:"grass",x:70,y:615,size:76,hp:1,maxHp:1,reward:{sprout:2}}
];
const forestEntities=[
 {id:"forest-tree",type:"tree",x:77,y:391,size:132,hp:3,maxHp:3,reward:{wood:4}},
 {id:"forest-rocks",type:"rocks",x:307,y:407,size:102,hp:3,maxHp:3,reward:{stone:4}},
 {id:"forest-berries",type:"berries",x:220,y:545,size:104,hp:2,maxHp:2,reward:{berry:4}},
 {id:"forest-grass",type:"grass",x:76,y:634,size:91,hp:1,maxHp:1,reward:{sprout:3}},
 {id:"forest-logs",type:"logs",x:308,y:660,size:100,hp:2,maxHp:2,reward:{wood:3}}
];
const groveEntities=[
 {id:"grove-tree",type:"tree",x:76,y:395,size:125,hp:3,maxHp:3,reward:{wood:3,berry:1}},
 {id:"grove-berries-a",type:"berries",x:312,y:423,size:102,hp:2,maxHp:2,reward:{berry:4}},
 {id:"grove-grass",type:"grass",x:80,y:590,size:90,hp:1,maxHp:1,reward:{sprout:3}},
 {id:"grove-berries-b",type:"berries",x:289,y:658,size:100,hp:2,maxHp:2,reward:{berry:4}},
 {id:"grove-logs",type:"logs",x:208,y:515,size:91,hp:2,maxHp:2,reward:{wood:3}}
];
const snowEntities=[
 {id:"snow-rocks-a",type:"rocks",x:76,y:393,size:111,hp:3,maxHp:3,reward:{stone:4}},
 {id:"snow-logs",type:"logs",x:306,y:430,size:100,hp:2,maxHp:2,reward:{wood:3}},
 {id:"snow-grass",type:"grass",x:74,y:604,size:90,hp:1,maxHp:1,reward:{sprout:3}},
 {id:"snow-rocks-b",type:"rocks",x:292,y:660,size:102,hp:3,maxHp:3,reward:{stone:4}},
 {id:"snow-berries",type:"berries",x:199,y:528,size:95,hp:2,maxHp:2,reward:{berry:3}}
];
const regionEntities={village:entities,forest:forestEntities,grove:groveEntities,snow:snowEntities};
const regions={village:{name:"햇살 마을",hint:"서식지와 가구를 만드는 곳"},forest:{name:"햇살 숲",hint:"다리를 고치면 열려요"},grove:{name:"꽃바람 숲",hint:"햇살 숲 자연물 세 곳 채집"},snow:{name:"눈꽃 들판",hint:"꽃바람 숲 자연물 세 곳 채집"}};
function activeEntities(){return regionEntities[state.area]||entities}
const chickCatalog=[
 {id:"base",name:"삐약이",asset:"base",status:"첫 둥지를 찾아온 마을의 첫 주민이에요.",need:"빈 둥지 1개 · 빈터 1곳 정리",ready:()=>nestCount()>=1&&state.cleared>=1},
 {id:"scout",name:"탐험삐약",asset:"scout",status:"새로운 길을 살피는 탐험가예요.",need:"빈 둥지 2개 · 텃밭 · 빈터 3곳",ready:()=>nestCount()>=2&&facilities.some(f=>f.type==="garden")&&state.cleared>=3},
 {id:"builder",name:"뚝딱삐약",asset:"builder",status:"무거운 자재를 옮기고 다리를 고칠 수 있어요.",need:"빈 둥지 3개 · 환경 Lv.2",ready:()=>nestCount()>=3&&state.level>=2},
 {id:"leaf",name:"풀잎삐약",asset:"leaf",status:"꽃바람 숲의 식물 돌보기를 좋아해요.",need:"빈 둥지 4개 · 햇살 숲 채집 3곳",ready:()=>nestCount()>=4&&state.forestCleared>=3},
 {id:"camera",name:"찰칵삐약",asset:"camera",status:"새 지역의 풍경을 기록해요.",need:"빈 둥지 5개 · 꽃바람 숲 채집 2곳",ready:()=>nestCount()>=5&&state.groveCleared>=2},
 {id:"snow",name:"눈송삐약",asset:"snow",status:"눈꽃 들판에서 온 차분한 친구예요.",need:"빈 둥지 6개 · 눈꽃 들판 채집 2곳",ready:()=>nestCount()>=6&&state.snowCleared>=2}
];
const chicks=[];
const facilities=[];
const recipes={
 nest:{name:"포근한 빈 둥지",asset:"nest",desc:"병아리 한 마리마다 하나씩 필요해요.",cost:{wood:2,sprout:1},size:92,level:1},
 campfire:{name:"포근한 모닥불",asset:"campfire",desc:"쉬면서 기운을 채워요.",cost:{wood:3,stone:2},size:94},
 workbench:{name:"나무 작업대",asset:"workbench",desc:"가끔 나무를 만들어요.",cost:{wood:4,stone:2},size:100},
 garden:{name:"작은 텃밭",asset:"garden",desc:"열매와 새싹을 길러요.",cost:{wood:2,sprout:2},size:106},
 lamp:{name:"마을 가로등",asset:"lamp",desc:"마을의 행복을 밝혀요.",cost:{wood:2,stone:1},size:91},
 picnic:{name:"소풍 탁자",asset:"picnic",desc:"병아리들의 쉬는 자리를 만들어요.",cost:{wood:3,berry:1},size:105,level:1},
 arch:{name:"꽃 아치",asset:"arch",desc:"꽃길을 꾸며 행복을 더해요.",cost:{wood:2,sprout:2},size:103,level:2},
 swing:{name:"꽃 그네",asset:"swing",desc:"병아리들과 놀며 행복을 올려요.",cost:{wood:3,stone:1,berry:1},size:108,level:2}
};
recipes.workbench.level=2;recipes.lamp.level=2;recipes.campfire.level=1;recipes.garden.level=1;
function nestCount(){return facilities.filter(f=>f.type==="nest").length}
function nextVisitor(){return chickCatalog.find(info=>!chicks.some(chick=>chick.id===info.id))}
function freeNest(){return facilities.find(f=>f.type==="nest"&&!f.occupant)}
function visitorReady(){const info=nextVisitor();return !!info&&!!freeNest()&&info.ready()}
function addChick(id,restored=false){const info=chickCatalog.find(entry=>entry.id===id);if(!info||chicks.some(chick=>chick.id===id))return;const index=chicks.length,chick={id,name:info.name,asset:info.asset,x:202,y:restored?430:286,tx:110+index%3*70,ty:440+Math.floor(index/3)*90,size:65,phase:index*1.8,status:info.status,arrivedAt:restored?-100:state.clock};chicks.push(chick);if(!facilities.some(f=>f.type==="nest"&&f.occupant===id)){const nest=freeNest();if(nest)nest.occupant=id}state.selectedChick=id}
function regionOpen(id){return id==="village"||id==="forest"&&state.bridgeRepaired||id==="grove"&&state.bridgeRepaired&&state.forestCleared>=3||id==="snow"&&state.bridgeRepaired&&state.forestCleared>=3&&state.groveCleared>=3}
const load=()=>Promise.all(Object.entries(source).map(([key,src])=>new Promise(resolve=>{const img=new Image();img.onload=()=>{assets[key]=img;resolve()};img.onerror=()=>resolve();img.src=src})));
function resize(){const rect=canvas.getBoundingClientRect();canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);ctx.setTransform(rect.width/W*dpr,0,0,rect.height/H*dpr,0,0);render()}
function drawContain(img,x,y,w,h=w,alpha=1){if(!img)return;const scale=Math.min(w/img.width,h/img.height),dw=img.width*scale,dh=img.height*scale;ctx.save();ctx.globalAlpha=alpha;ctx.drawImage(img,x+(w-dw)/2,y+(h-dh)/2,dw,dh);ctx.restore()}
function drawBackground(){if(!assets.bg){ctx.fillStyle="#dff2a8";ctx.fillRect(0,0,W,H);return}const scale=Math.max(W/assets.bg.width,H/assets.bg.height),dw=assets.bg.width*scale,dh=assets.bg.height*scale;if(state.area==="forest"||state.area==="snow"){ctx.save();ctx.translate(W,H);ctx.rotate(Math.PI);ctx.drawImage(assets.bg,(W-dw)/2,(H-dh)/2,dw,dh);ctx.restore()}else ctx.drawImage(assets.bg,(W-dw)/2,(H-dh)/2,dw,dh);if(state.area==="forest"){ctx.fillStyle="#4a98651d";ctx.fillRect(0,0,W,H);drawContain(assets.tree,-47,192,104);drawContain(assets.tree,340,260,104)}else if(state.area==="grove"){ctx.fillStyle="#f58da929";ctx.fillRect(0,0,W,H);drawContain(assets.arch,7,205,100);drawContain(assets.arch,322,242,95);for(let i=0;i<16;i++){ctx.fillStyle=i%2?"#ffdfe9a0":"#fff2c2b0";ctx.beginPath();ctx.ellipse((i*83+24)%W,285+(i*97)%420,3,5,.5,0,Math.PI*2);ctx.fill()}}else if(state.area==="snow"){ctx.fillStyle="#dff5ff88";ctx.fillRect(0,0,W,H);for(let i=0;i<30;i++){ctx.fillStyle="#ffffff9c";ctx.beginPath();ctx.arc((i*107+19)%W,275+(i*71)%440,i%3+2,0,Math.PI*2);ctx.fill()}}}
function shadowEllipse(x,y,rx,ry,alpha=.18){ctx.save();ctx.fillStyle=`rgba(48,73,42,${alpha})`;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill();ctx.restore()}
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function drawEntity(e){if(e.hp<=0&&e.fade<=0)return;const shake=e.shake>0?Math.sin(state.clock*55)*4:0,alpha=e.fade===undefined?1:Math.max(0,e.fade/.38);shadowEllipse(e.x,e.y+e.size*.28,e.size*.29,e.size*.1,.14*alpha);drawContain(assets[e.type],e.x-e.size/2+shake,e.y-e.size*.68,e.size,e.size,alpha);if(e.hp>0&&e.hp<e.maxHp){const w=43,x=e.x-w/2,y=e.y-e.size*.49;ctx.fillStyle="#fff9e6";roundRect(x-2,y-2,w+4,9,5);ctx.fill();ctx.fillStyle="#e8b9a7";roundRect(x,y,w,5,3);ctx.fill();ctx.fillStyle="#62aa50";roundRect(x,y,w*(e.hp/e.maxHp),5,3);ctx.fill()}}
function drawFacility(f){shadowEllipse(f.x,f.y+f.size*.25,f.size*.28,f.size*.1);drawContain(assets[f.type],f.x-f.size/2,f.y-f.size*.66,f.size,f.size);if(f.cooldown>state.clock){const remain=Math.ceil(f.cooldown-state.clock);ctx.fillStyle="#fffdf2e8";roundRect(f.x-20,f.y-f.size*.5,40,18,9);ctx.fill();ctx.fillStyle="#596258";ctx.font="900 9px sans-serif";ctx.textAlign="center";ctx.fillText(`${remain}초`,f.x,f.y-f.size*.5+12)}}
function drawBridgeMarker(){ctx.save();const y=222+Math.sin(state.clock*2)*2;ctx.shadowColor="#31462d55";ctx.shadowBlur=9;ctx.fillStyle=state.bridgeRepaired?"#5ca64c":"#d69049";roundRect(245,y-13,99,29,11);ctx.fill();ctx.lineWidth=2;ctx.strokeStyle="#fff7d6";ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle="#fff";ctx.font="900 11px sans-serif";ctx.textAlign="center";ctx.fillText(state.bridgeRepaired?"지역 이동":"다리 수리",294,y+6);if(!state.bridgeRepaired&&state.area==="village"){ctx.fillStyle="#765039";ctx.fillRect(266,162,7,16);ctx.fillRect(305,169,7,15);ctx.strokeStyle="#e0c196";ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(269,171);ctx.lineTo(311,178);ctx.stroke()}ctx.restore()}
function drawChick(c){const bob=Math.sin(state.clock*3+c.phase)*2.4;shadowEllipse(c.x,c.y+25,c.size*.25,c.size*.08,.16);ctx.save();ctx.shadowColor="#3f52373b";ctx.shadowBlur=6;ctx.shadowOffsetY=3;drawContain(assets[c.asset],c.x-c.size/2,c.y-c.size*.62+bob,c.size,c.size);ctx.restore();if(state.clock-c.arrivedAt<5){ctx.fillStyle="#fffdf2";roundRect(c.x-31,c.y-c.size*.68,62,20,10);ctx.fill();ctx.fillStyle="#4c6545";ctx.font="900 9px sans-serif";ctx.textAlign="center";ctx.fillText("새 친구!",c.x,c.y-c.size*.68+13)}}
function tileAt(x,y){return villageTiles.find(tile=>Math.abs(x-tile.x)/45+Math.abs(y-tile.y)/30<=1)}
function tileOccupied(tile){return facilities.some(f=>f.tileId===tile.id)}
function nearestFreeTile(x,y,used=new Set()){return buildTiles.filter(tile=>!used.has(tile.id)&&!tileOccupied(tile)).sort((a,b)=>Math.hypot(a.x-x,a.y-y)-Math.hypot(b.x-x,b.y-y))[0]}
function drawDiamond(tile,fill,stroke,width=1){ctx.beginPath();ctx.moveTo(tile.x,tile.y-30);ctx.lineTo(tile.x+45,tile.y);ctx.lineTo(tile.x,tile.y+30);ctx.lineTo(tile.x-45,tile.y);ctx.closePath();ctx.fillStyle=fill;ctx.fill();ctx.strokeStyle=stroke;ctx.lineWidth=width;ctx.stroke()}
function drawGroundGrid(){if(state.area!=="village")return;ctx.save();for(const tile of villageTiles){const occupied=tile.kind==="build"&&tileOccupied(tile);if(state.buildMode){const active=state.pointer?.id===tile.id;drawDiamond(tile,tile.kind==="nature"?"#dfaa6480":occupied?"#667b7055":active?"#f7f7bdcc":"#dcffb999",tile.kind==="nature"?"#ae753f":occupied?"#829484":active?"#ffffff":"#5caa57",active?3:2)}else if(tile.kind==="nature")drawDiamond(tile,"#e9bb7240","#b48f5d44")}ctx.restore()}
function drawBuildGhost(){if(!state.buildMode||!state.pointer||state.pointer.kind!=="build"||tileOccupied(state.pointer))return;const r=recipes[state.buildMode],x=state.pointer.x,y=state.pointer.y;ctx.save();ctx.globalAlpha=.7;shadowEllipse(x,y+r.size*.25,r.size*.3,r.size*.12,.16);drawContain(assets[r.asset],x-r.size/2,y-r.size*.66,r.size,r.size);ctx.restore()}
function drawEffects(){for(const e of state.effects){const t=e.life/e.max;ctx.save();ctx.globalAlpha=Math.min(1,t*2);ctx.fillStyle=e.color||"#fff";ctx.strokeStyle="#493f2f";ctx.lineWidth=3;ctx.font="900 14px sans-serif";ctx.textAlign="center";ctx.strokeText(e.text,e.x,e.y);ctx.fillText(e.text,e.x,e.y);ctx.restore()}for(const p of state.particles){ctx.save();ctx.globalAlpha=Math.max(0,p.life/.65);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill();ctx.restore()}}
function render(){ctx.clearRect(0,0,W,H);drawBackground();drawGroundGrid();drawBridgeMarker();const layers=[];activeEntities().filter(e=>e.hp>0||e.fade>0).forEach(e=>layers.push({y:e.y,draw:()=>drawEntity(e)}));if(state.area==="village")facilities.forEach(f=>layers.push({y:f.y,draw:()=>drawFacility(f)}));if(state.area==="village")chicks.forEach(c=>layers.push({y:c.y,draw:()=>drawChick(c)}));layers.sort((a,b)=>a.y-b.y).forEach(l=>l.draw());drawBuildGhost();drawEffects()}
function update(dt){state.clock+=dt;for(const e of [...entities,...forestEntities]){e.shake=Math.max(0,(e.shake||0)-dt);if(e.hp<=0)e.fade=Math.max(0,(e.fade??.38)-dt)}for(const e of state.effects){e.life-=dt;e.y-=22*dt}state.effects=state.effects.filter(e=>e.life>0);for(const p of state.particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=55*dt}state.particles=state.particles.filter(p=>p.life>0);for(const c of chicks){const dx=c.tx-c.x,dy=c.ty-c.y,dist=Math.hypot(dx,dy);if(dist<5){const points=[[115,440],[205,420],[287,484],[112,610],[225,642],[300,580]],next=points[(Math.floor(state.clock/2)+Math.round(c.phase*3))%points.length];c.tx=next[0];c.ty=next[1]}else{const speed=c.id==="builder"?13:10;c.x+=dx/dist*speed*dt;c.y+=dy/dist*speed*dt}}}
function canvasPoint(event){const r=canvas.getBoundingClientRect();return{x:(event.clientX-r.left)/r.width*W,y:(event.clientY-r.top)/r.height*H}}
function hitEntity(p){return entities.filter(e=>e.hp>0).reverse().find(e=>Math.hypot(p.x-e.x,p.y-(e.y-e.size*.15))<e.size*.43)}
function hitChick(p){return [...chicks].reverse().find(c=>Math.hypot(p.x-c.x,p.y-(c.y-c.size*.18))<c.size*.48)}
function hitFacility(p){return [...facilities].reverse().find(f=>Math.hypot(p.x-f.x,p.y-(f.y-f.size*.15))<f.size*.42)}
function hitWorld(p){const hits=[];for(const e of activeEntities().filter(e=>e.hp>0))if(Math.hypot(p.x-e.x,p.y-(e.y-e.size*.15))<e.size*.43)hits.push({kind:"entity",item:e,y:e.y});if(state.area==="village"){for(const f of facilities)if(Math.hypot(p.x-f.x,p.y-(f.y-f.size*.15))<f.size*.42)hits.push({kind:"facility",item:f,y:f.y});for(const c of chicks)if(Math.hypot(p.x-c.x,p.y-(c.y-c.size*.18))<c.size*.48)hits.push({kind:"chick",item:c,y:c.y})}return hits.sort((a,b)=>b.y-a.y)[0]}
function validPlacement(x,y){const tile=tileAt(x,y);return state.area==="village"&&!!tile&&tile.kind==="build"&&!tileOccupied(tile)}
function burst(x,y,color="#f2c650"){for(let i=0;i<9;i++){const angle=Math.PI*2*i/9+i*.17;state.particles.push({x,y:y-14,vx:Math.cos(angle)*(24+4*i),vy:Math.sin(angle)*(24+4*i)-28,r:2+i%3,life:.65,color})}}
function floatText(x,y,text,color="#fff4a8"){state.effects.push({x,y,text,color,life:.85,max:.85})}
function gainXP(amount){state.xp+=amount;const next=state.xp>=34?3:state.xp>=14?2:1;if(next>state.level){state.level=next;toast(`환경 레벨 ${next}! 새 제작법이 열렸어요.`);burst(195,370,"#ffdc64")}}
function gather(e){if(state.energy<=0){toast("기운이 없어요. 다음 날을 시작해 회복해 주세요.");return}state.energy--;e.hp--;e.shake=.22;burst(e.x,e.y-e.size*.15);floatText(e.x,e.y-e.size*.55,"톡!");if(e.hp<=0){Object.entries(e.reward).forEach(([key,value])=>{state.resources[key]+=value;floatText(e.x,e.y-e.size*.36,`+${value} ${rewardNames[key]}`,"#fff4a8")});const key={village:"cleared",forest:"forestCleared",grove:"groveCleared",snow:"snowCleared"}[state.area];state[key]++;gainXP(3);burst(e.x,e.y-e.size*.12,"#8ecb65");toast(`${Object.entries(e.reward).map(([k,v])=>`${rewardNames[k]} ${v}개`).join(", ")}를 모았어요`);if(state.area==="forest"&&state.forestCleared===3||state.area==="grove"&&state.groveCleared===3){state.happiness+=10;toast("새 지역으로 가는 길이 열렸어요. 표지를 눌러보세요.")}}syncUI();checkProgress();saveGame()}
function placeFacility(x,y){const tile=tileAt(x,y);if(!tile){toast("초록 격자 칸을 눌러주세요.");return}if(tile.kind==="nature"){toast("갈색 칸은 자연물이 다시 자라는 자리예요.");return}if(!validPlacement(x,y)){toast("이미 시설이 있는 칸이에요. 다른 초록 칸을 골라주세요.");return}const type=state.buildMode,r=recipes[type];if(!canAfford(r.cost)){cancelBuild();toast("재료가 부족해요.");return}Object.entries(r.cost).forEach(([key,value])=>state.resources[key]-=value);facilities.push({id:`${type}-${facilities.length+1}`,type,x:tile.x,y:tile.y,tileId:tile.id,size:r.size,cooldown:0});state.buildMode=null;state.pointer=null;document.getElementById("mode-banner").hidden=true;gainXP(type==="nest"||type==="garden"?5:3);burst(tile.x,tile.y,"#ffd45c");floatText(tile.x,tile.y-r.size*.55,"완성!","#fff4a8");toast(`${r.name} 완성!`);syncUI();checkProgress();saveGame()}
function useFacility(f){const r=recipes[f.type];if(f.type==="nest"){openSheet("habitat-sheet");return}if(f.cooldown>state.clock){toast(`${r.name}은 잠시 뒤에 다시 이용할 수 있어요.`);return}if(f.type==="campfire"){state.energy=Math.min(state.maxEnergy,state.energy+3);speak("모닥불이 따뜻해요. 기운을 3 회복했어요!");f.cooldown=12}else if(f.type==="garden"){state.resources.berry++;state.resources.sprout++;speak("텃밭에서 열매와 새싹을 수확했어요!");f.cooldown=15}else if(f.type==="workbench"){state.resources.wood++;speak("작업대에서 쓸 만한 나무를 다듬었어요!");f.cooldown=12}else if(f.type==="picnic"){state.energy=Math.min(state.maxEnergy,state.energy+2);state.happiness+=2;speak("소풍 탁자에서 쉬며 기운과 행복이 올랐어요!");f.cooldown=13}else if(f.type==="swing"){state.happiness+=4;state.plays++;speak("꽃 그네에서 놀아서 마을 행복이 올랐어요!");f.cooldown=12}else{state.happiness+=f.type==="arch"?3:2;speak(f.type==="arch"?"꽃 아치 덕분에 마을이 화사해졌어요!":"불빛을 보고 병아리들이 행복해해요!");f.cooldown=10}burst(f.x,f.y-f.size*.2);syncUI();saveGame()}
function openFriend(chick=chicks.find(c=>c.id===state.selectedChick)||chicks[0]){const empty=!chick;document.getElementById("friend-empty").hidden=!empty;document.getElementById("friend-profile").hidden=empty;document.getElementById("friend-actions").hidden=empty;document.getElementById("friend-name").textContent=empty?"아직 빈 마을":chick.name;if(chick){state.selectedChick=chick.id;document.getElementById("friend-image").src=source[chick.asset];document.getElementById("friend-status").textContent=chick.status}document.getElementById("friend-roster").innerHTML=chicks.map(c=>`<button class="${c.id===chick?.id?"active":""}" data-chick="${c.id}"><img src="${source[c.asset]}" alt="">${c.name}</button>`).join("");document.querySelectorAll("[data-chick]").forEach(button=>button.onclick=()=>openFriend(chicks.find(c=>c.id===button.dataset.chick)));openSheet("friend-sheet")}
function friendAction(action){const chick=chicks.find(c=>c.id===state.selectedChick);if(!chick)return;if(action==="play"){state.plays++;state.happiness+=2;speak(`${chick.name}: 같이 뛰어놀아서 신나요!`);burst(chick.x,chick.y-24,"#ff8d84")}else if(action==="feed"){if(state.resources.berry<1){toast("열매가 없어요. 열매 덤불을 정리해 보세요.");return}state.resources.berry--;state.happiness+=3;speak(`${chick.name}: 새콤달콤해서 맛있어요!`)}else{state.energy=Math.min(state.maxEnergy,state.energy+2);speak(`${chick.name}와 잠깐 쉬며 기운을 회복했어요.`)}closeSheets();syncUI();checkProgress();saveGame()}
function canAfford(cost){return Object.entries(cost).every(([key,value])=>state.resources[key]>=value)}
function costText(cost){return Object.entries(cost).map(([k,v])=>`<span class="${state.resources[k]<v?"missing":""}">${rewardNames[k]} ${state.resources[k]}/${v}</span>`).join("")}
function renderRecipes(){document.getElementById("recipe-list").innerHTML=Object.entries(recipes).map(([key,r])=>{const unlocked=state.level>=r.level,affordable=canAfford(r.cost),placed=facilities.some(f=>f.type===key);return `<button class="recipe ${affordable&&unlocked?"affordable":"locked"} ${placed&&key!=="nest"?"placed":""}" data-recipe="${key}"><img src="${source[r.asset]}" alt=""><strong>${r.name}${key==="nest"?` · ${nestCount()}개`:""}</strong><small>${r.desc}</small><span class="recipe-cost">${costText(r.cost)}</span>${unlocked?"":`<span class="lock-label">환경 Lv.${r.level}</span>`}</button>`}).join("");document.querySelectorAll("[data-recipe]").forEach(button=>button.onclick=()=>selectRecipe(button.dataset.recipe))}
function selectRecipe(type){const r=recipes[type];if(state.area!=="village"){toast("시설은 마을에서 놓을 수 있어요. 지역 표지로 돌아가세요.");return}if(state.level<r.level){toast(`환경 레벨 ${r.level}에서 열려요.`);return}if(type==="nest"&&nestCount()>=chickCatalog.length){toast("현재 방문할 수 있는 병아리의 둥지는 모두 준비했어요.");return}if(!canAfford(r.cost)){toast("부족한 재료를 확인하고 마을에서 모아주세요.");return}if(!nearestFreeTile(205,505)){toast("설치할 빈 칸이 없어요.");return}closeSheets();state.buildMode=type;state.pointer=nearestFreeTile(205,505);document.getElementById("mode-title").textContent=`${r.name} 놓기`;document.getElementById("mode-banner").hidden=false;toast("초록 칸을 눌러 설치하세요. 갈색 칸은 채집 구역이에요.")}
function cancelBuild(){state.buildMode=null;state.pointer=null;document.getElementById("mode-banner").hidden=true}
function hasNest(){return nestCount()>0}
function hasNearbyGarden(){return facilities.filter(f=>f.type==="nest").some(nest=>facilities.some(f=>f.type==="garden"&&Math.hypot(f.x-nest.x,f.y-nest.y)<=145))}
function habitatConditions(){const info=nextVisitor();if(!info)return[{name:"모든 병아리 방문",detail:`주민 ${chicks.length}/${chickCatalog.length}`,done:true}];const number=chickCatalog.indexOf(info)+1,rows=[{name:`${number}번째 빈 둥지`,detail:`현재 ${nestCount()}개 · 주민 ${chicks.length}마리`,done:!!freeNest()}];if(info.id==="base")rows.push({name:"마을 빈터 1곳 정리",detail:`${state.cleared}/1`,done:state.cleared>=1});if(info.id==="scout")rows.push({name:"텃밭과 빈터 3곳",detail:`텃밭 ${facilities.some(f=>f.type==="garden")?"완료":"필요"} · 정리 ${state.cleared}/3`,done:facilities.some(f=>f.type==="garden")&&state.cleared>=3});if(info.id==="builder")rows.push({name:"환경 레벨 2",detail:`현재 Lv.${state.level}`,done:state.level>=2});if(info.id==="leaf")rows.push({name:"햇살 숲 채집 3곳",detail:`${state.forestCleared}/3`,done:state.forestCleared>=3});if(info.id==="camera")rows.push({name:"꽃바람 숲 채집 2곳",detail:`${state.groveCleared}/2`,done:state.groveCleared>=2});if(info.id==="snow")rows.push({name:"눈꽃 들판 채집 2곳",detail:`${state.snowCleared}/2`,done:state.snowCleared>=2});return rows}
function conditionHTML(rows){return rows.map(row=>`<div class="condition-row ${row.done?"done":""}"><i>${row.done?"✓":"·"}</i><span>${row.name}</span><b>${row.done?"충족":row.detail}</b></div>`).join("")}
function renderHabitat(){const info=nextVisitor();document.getElementById("habitat-copy").textContent=info?`다음 손님: ${info.name} · ${info.need}`:"지금 준비된 병아리가 모두 마을에 왔어요.";document.getElementById("habitat-conditions").innerHTML=conditionHTML(habitatConditions());document.getElementById("habitat-note").textContent=info?(visitorReady()?"조건 완료! 다음 날을 누르면 이 병아리 한 마리가 찾아와요.":"조건을 채우면 다음 날 한 마리씩 확정 방문해요."):`둥지 ${nestCount()}개 · 주민 ${chicks.length}마리`}
function bridgeConditions(){return[{name:"건축가 병아리",detail:"세 번째 주민으로 초대",done:chicks.some(c=>c.id==="builder")},{name:"나무 2개",detail:`보유 ${state.resources.wood}/2`,done:state.resources.wood>=2},{name:"돌 2개",detail:`보유 ${state.resources.stone}/2`,done:state.resources.stone>=2}]}
function renderBridge(){document.getElementById("bridge-conditions").innerHTML=conditionHTML(bridgeConditions());const button=document.getElementById("repair-button");button.disabled=state.bridgeRepaired||!bridgeConditions().every(c=>c.done);button.textContent=state.bridgeRepaired?"복구 완료 · 숲길이 열렸어요":"다리 복구하기"}
function questData(){return[
 {name:"첫 둥지 만들기",desc:"빈 둥지가 있어야 첫 병아리가 와요.",current:Math.min(nestCount(),1),goal:1},
 {name:"첫 병아리 맞이하기",desc:"빈터를 정리한 뒤 다음 날을 누르세요.",current:Math.min(chicks.length,1),goal:1},
 {name:"주민 세 마리 맞이하기",desc:"병아리마다 새 둥지를 준비하세요.",current:Math.min(chicks.length,3),goal:3},
 {name:"건축가와 다리 복구",desc:"세 번째 병아리의 건축 특기가 필요해요.",current:state.bridgeRepaired?1:0,goal:1},
 {name:"햇살 숲 탐험",desc:"숲 자연물 세 곳을 채집하세요.",current:Math.min(state.forestCleared,3),goal:3},
 {name:"꽃바람 숲 탐험",desc:"새로 열린 숲의 자연물 세 곳을 채집하세요.",current:Math.min(state.groveCleared,3),goal:3},
 {name:"눈꽃 들판 탐험",desc:"마지막 지역의 자연물 두 곳을 채집하세요.",current:Math.min(state.snowCleared,2),goal:2},
 {name:"병아리 여섯 마리 맞이하기",desc:"둥지를 늘려 주민을 한 마리씩 모으세요.",current:Math.min(chicks.length,6),goal:6}
]}
function renderQuests(){const quests=questData();document.getElementById("quest-list").innerHTML=quests.map((q,i)=>{const done=q.current>=q.goal;return `<article class="quest-row ${done?"done":""}"><i>${done?"✓":i+1}</i><span><strong>${q.name}</strong><small>${q.desc}</small></span><b>${q.current}/${q.goal}</b></article>`}).join("");const done=quests.filter(q=>q.current>=q.goal).length;document.getElementById("quest-total").textContent=`${done}/${quests.length}`;document.getElementById("quest-summary").textContent=done===quests.length?"마을 탐험 완료!":quests.find(q=>q.current<q.goal).name;document.querySelector(".quest-reward strong").textContent="여섯 병아리 · 새 가구 · 네 지역"}
function checkProgress(){const wasPending=state.visitorPending;state.visitorPending=visitorReady();if(state.visitorPending&&!wasPending)toast(`${nextVisitor().name} 방문 준비 완료! 다음 날을 시작해 주세요.`);renderQuests();renderHabitat();renderBridge();syncUI()}
function nextDay(){const info=visitorReady()?nextVisitor():null;state.day++;state.energy=state.maxEnergy;for(const e of Object.values(regionEntities).flat()){e.hp=e.maxHp;e.fade=undefined;e.shake=0}for(const f of facilities)f.cooldown=0;if(info){addChick(info.id);state.happiness+=5;gainXP(5);burst(202,274,"#ffd85b");toast(`새 주민 ${info.name} 방문! 현재 ${chicks.length}마리`)}else toast(`DAY ${state.day} · 기운이 회복되고 자원이 다시 자랐어요.`);checkProgress();saveGame()}
function repairBridge(){if(state.bridgeRepaired)return;if(!bridgeConditions().every(c=>c.done)){renderBridge();toast("건축가와 나무 2개, 돌 2개가 필요해요.");return}state.resources.wood-=2;state.resources.stone-=2;state.bridgeRepaired=true;state.happiness+=20;gainXP(10);closeSheets();burst(294,210,"#ffdf79");toast("다리 복구 완료! 표지를 눌러 숲으로 가보세요.");checkProgress();saveGame()}
function renderRegions(){document.getElementById("region-list").innerHTML=Object.entries(regions).map(([id,region])=>`<button data-region="${id}" class="${state.area===id?"current":""}" ${regionOpen(id)?"":"disabled"}><strong>${regionOpen(id)?"↗":"●"} ${region.name}${state.area===id?" · 현재 지역":""}</strong><small>${regionOpen(id)?id==="village"?"둥지와 가구 설치":id==="forest"?`채집 ${Math.min(state.forestCleared,3)}/3`:id==="grove"?`채집 ${Math.min(state.groveCleared,3)}/3`:`채집 ${Math.min(state.snowCleared,2)}/2`:region.hint}</small></button>`).join("");document.querySelectorAll("[data-region]").forEach(button=>button.onclick=()=>goToRegion(button.dataset.region))}
function goToRegion(id){if(!regionOpen(id)){toast(`${regions[id].name}은 아직 열리지 않았어요.`);return}state.area=id;cancelBuild();closeSheets();document.getElementById("area-name").textContent=regions[id].name;toast(`${regions[id].name}에 도착했어요.`);saveGame()}
function travel(){if(!state.bridgeRepaired){openSheet("bridge-sheet");return}renderRegions();openSheet("region-sheet")}
function renderBag(){const items=[{k:"wood",icon:"◆"},{k:"stone",icon:"●"},{k:"sprout",icon:"♣"},{k:"berry",icon:"●"}];document.getElementById("bag-grid").innerHTML=items.map(i=>`<article class="bag-item"><b class="${i.k}">${i.icon}</b><strong>${state.resources[i.k]}</strong><small>${rewardNames[i.k]}</small></article>`).join("")}
function syncUI(){for(const key of Object.keys(state.resources))document.getElementById(`${key}-count`).textContent=state.resources[key];document.getElementById("energy-count").textContent=state.energy;document.getElementById("happiness-count").textContent=state.happiness;document.getElementById("day-count").textContent=state.day;document.getElementById("friends-count").textContent=`친구 ${chicks.length}`;document.getElementById("level-count").textContent=state.level;const start=state.level===1?0:state.level===2?14:34,end=state.level===1?14:state.level===2?34:34;document.getElementById("level-progress").style.width=state.level===3?"100%":`${Math.min(100,(state.xp-start)/(end-start)*100)}%`;renderQuests();renderHabitat();renderBridge();renderBag();renderRecipes()}
function openSheet(id){closeSheets();if(id==="build-sheet")renderRecipes();if(id==="quest-sheet")renderQuests();if(id==="bag-sheet")renderBag();if(id==="habitat-sheet")renderHabitat();if(id==="bridge-sheet")renderBridge();if(id==="region-sheet")renderRegions();document.getElementById(id).hidden=false}
function closeSheets(){document.querySelectorAll(".bottom-sheet").forEach(sheet=>sheet.hidden=true)}
function toast(message){const el=document.getElementById("toast");el.textContent=message;el.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove("show"),1900)}
function speak(message){const el=document.getElementById("speech-bubble");el.textContent=message;el.classList.add("show");clearTimeout(speak.timer);speak.timer=setTimeout(()=>el.classList.remove("show"),1900)}
function onCanvas(event){if(state.intro)return;const p=canvasPoint(event);if(state.buildMode){placeFacility(p.x,p.y);return}if(p.x>=242&&p.x<=346&&p.y>=197&&p.y<=252){travel();return}const hit=hitWorld(p);if(!hit){speak("자연물을 채집하거나 빈 둥지를 지어 첫 병아리를 맞이해 보세요.");return}if(hit.kind==="chick")openFriend(hit.item);else if(hit.kind==="facility")useFacility(hit.item);else gather(hit.item)}
canvas.addEventListener("pointerdown",event=>{event.preventDefault();onCanvas(event)});canvas.addEventListener("pointermove",event=>{if(state.buildMode){const p=canvasPoint(event);state.pointer=tileAt(p.x,p.y)||null;render()}});
document.getElementById("start-game").onclick=()=>{state.intro=false;document.getElementById("intro-card").hidden=true;toast("첫 병아리는 아직 없어요. 빈 둥지를 준비해 주세요.");saveGame()};
document.getElementById("build-button").onclick=()=>openSheet("build-sheet");document.getElementById("bag-button").onclick=()=>openSheet("bag-sheet");document.getElementById("friends-button").onclick=()=>openFriend();document.getElementById("quest-button").onclick=()=>openSheet("quest-sheet");document.getElementById("cancel-build").onclick=cancelBuild;
document.getElementById("day-button").onclick=nextDay;document.getElementById("level-button").onclick=()=>toast(state.level===3?"환경 레벨 3 · 숲길 복구 단계예요.":`환경 경험치 ${state.xp}/${state.level===1?14:34} · 채집과 제작으로 성장해요.`);document.getElementById("repair-button").onclick=repairBridge;
document.getElementById("restart-button").onclick=event=>{const button=event.currentTarget;if(!button.classList.contains("armed")){button.classList.add("armed");button.textContent="진행 기록 삭제 · 한 번 더 누르기";clearTimeout(button.resetTimer);button.resetTimer=setTimeout(()=>{button.classList.remove("armed");button.textContent="처음부터 새로 시작"},5000);return}localStorage.removeItem("chick-village-save-v2");location.reload()};
document.querySelectorAll("[data-close]").forEach(button=>button.onclick=()=>document.getElementById(button.dataset.close).hidden=true);document.querySelectorAll("[data-friend-action]").forEach(button=>button.onclick=()=>friendAction(button.dataset.friendAction));
document.addEventListener("keydown",event=>{if(event.key==="Escape"){closeSheets();cancelBuild()}});addEventListener("resize",resize);
window.advanceTime=ms=>{for(let i=0,n=Math.max(1,Math.round(ms/(1000/60)));i<n;i++)update(1/60);render()};
window.render_game_to_text=()=>JSON.stringify({coordinate_system:"portrait canvas 390x844; origin top-left",mode:state.intro?"intro":state.buildMode?`placing ${state.buildMode}`:"explore",area:state.area,regions:Object.keys(regions).map(id=>({id,open:regionOpen(id)})),day:state.day,energy:`${state.energy}/${state.maxEnergy}`,resources:state.resources,happiness:state.happiness,environment:{level:state.level,xp:state.xp},habitat:{nests:nestCount(),residents:chicks.length,next:nextVisitor()?.name||null,conditions:habitatConditions(),visitorPending:state.visitorPending},bridge:{repaired:state.bridgeRepaired,conditions:bridgeConditions()},quests:questData(),obstacles:activeEntities().filter(e=>e.hp>0).map(e=>({id:e.id,type:e.type,x:Math.round(e.x),y:Math.round(e.y),hp:`${e.hp}/${e.maxHp}`})),grid:state.area==="village"?{buildable:buildTiles.length,available:buildTiles.filter(tile=>!tileOccupied(tile)).length,nature:villageTiles.filter(tile=>tile.kind==="nature").map(tile=>({id:tile.id,x:tile.x,y:tile.y})),selected:state.pointer?.id||null}:null,facilities:state.area==="village"?facilities.map(f=>({type:f.type,tileId:f.tileId,occupant:f.occupant||null,x:Math.round(f.x),y:Math.round(f.y),ready:f.cooldown<=state.clock})):[],chicks:state.area==="village"?chicks.map(c=>({id:c.id,name:c.name,x:Math.round(c.x),y:Math.round(c.y)})):[],controls:"Gather resources, build one empty nest per chick, satisfy habitat conditions, then tap DAY to welcome one chick; tap the region sign for the map."});
function saveGame(){try{localStorage.setItem("chick-village-save-v2",JSON.stringify({schema:3,day:state.day,area:state.area,energy:state.energy,resources:state.resources,cleared:state.cleared,forestCleared:state.forestCleared,groveCleared:state.groveCleared,snowCleared:state.snowCleared,plays:state.plays,happiness:state.happiness,xp:state.xp,level:state.level,bridgeRepaired:state.bridgeRepaired,chickIds:chicks.map(c=>c.id),facilities:facilities.map(({id,type,tileId,x,y,size,occupant})=>({id,type,tileId,x,y,size,occupant})),obstacles:Object.values(regionEntities).flat().map(({id,hp})=>({id,hp}))}))}catch{}}
function restoreGame(){try{const raw=localStorage.getItem("chick-village-save-v2");if(!raw)return;const saved=JSON.parse(raw);for(const key of["day","area","energy","cleared","forestCleared","groveCleared","snowCleared","plays","happiness","xp","level","bridgeRepaired"])if(saved[key]!==undefined)state[key]=saved[key];if(!regions[state.area]||!regionOpen(state.area))state.area="village";for(const key of Object.keys(state.resources))if(Number.isFinite(saved.resources?.[key]))state.resources[key]=saved.resources[key];for(const data of saved.obstacles||[]){const target=Object.values(regionEntities).flat().find(e=>e.id===data.id);if(target){target.hp=data.hp;target.fade=data.hp<=0?0:undefined}}const used=new Set();for(const data of saved.facilities||[]){if(!recipes[data.type])continue;let tile=buildTiles.find(t=>t.id===data.tileId&&!used.has(t.id));if(!tile)tile=nearestFreeTile(Number(data.x)||205,Number(data.y)||505,used);if(!tile)continue;used.add(tile.id);facilities.push({...data,x:tile.x,y:tile.y,tileId:tile.id,size:recipes[data.type].size,cooldown:0})}const ids=Array.isArray(saved.chickIds)?saved.chickIds:(saved.visitorArrived?["base","scout","builder"]:[]);for(const id of ids){if(!facilities.some(f=>f.type==="nest"&&!f.occupant)&&!facilities.some(f=>f.type==="nest"&&f.occupant===id)){const tile=nearestFreeTile(205,505,used);if(tile){used.add(tile.id);facilities.push({id:`nest-migrated-${id}`,type:"nest",x:tile.x,y:tile.y,tileId:tile.id,size:recipes.nest.size,cooldown:0})}}addChick(id,true)}state.visitorPending=visitorReady();state.intro=false;document.getElementById("intro-card").hidden=true;document.getElementById("area-name").textContent=regions[state.area].name}catch{}}
restoreGame();load().then(()=>{resize();syncUI()});let previous=performance.now();function loop(now){update(Math.min(.034,(now-previous)/1000));previous=now;render();requestAnimationFrame(loop)}requestAnimationFrame(loop);
})();
