(()=>{"use strict";
const canvas=document.getElementById("game-canvas"),ctx=canvas.getContext("2d"),W=390,H=844,dpr=Math.max(1,Math.min(devicePixelRatio||1,2));
const source={bg:"assets/game/meadow-base.png",tree:"assets/game/tree.png",logs:"assets/game/logs.png",rocks:"assets/game/rocks.png",grass:"assets/game/grass.png",berries:"assets/game/berries.png",campfire:"assets/game/campfire.png",workbench:"assets/game/workbench.png",lamp:"assets/game/lamp.png",garden:"assets/game/garden.png",picnic:"assets/game/picnic-table.png",arch:"assets/game/flower-arch.png",swing:"assets/game/garden-swing.png",nest:"assets/unity/nest.png",base:"assets/unity/chick-base.png",scout:"assets/unity/chick-scout.png",builder:"assets/unity/chick-builder.png",leaf:"assets/unity/chick-leaf.png",camera:"assets/unity/chick-camera.png",cowboy:"assets/unity/chick-cowboy.png",snow:"assets/unity/chick-snow.png"},assets={};
const rewardNames={wood:"나무",stone:"돌",sprout:"새싹",berry:"열매",resin:"숲의 수지",petal:"꽃잎",crystal:"눈 결정"};
const state={clock:0,dayClock:0,intro:true,discardingSave:false,day:1,area:"village",energy:12,maxEnergy:12,resources:{wood:2,stone:0,sprout:1,berry:0,resin:0,petal:0,crystal:0},acorns:0,claimedQuests:[],dailyCleanup:false,dailyCare:false,dailySkills:{},dailyBond:{},bonds:{},leads:{},encounterMisses:0,rngSeed:Date.now()>>>0,guest:null,lastEncounter:"",profileId:null,buildTab:"craft",movingFacility:null,selectedNestId:null,cleared:0,forestCleared:0,groveCleared:0,snowCleared:0,plays:0,happiness:0,xp:0,level:1,buildMode:null,visitorPending:false,bridgeRepaired:false,forestTrailFound:false,groveBloomed:false,icePlayground:false,photoTaken:false,selectedChick:null,effects:[],particles:[],focusedEntity:null};
const lifeData=window.CHICK_LIFE_DATA||{};
function subjectName(name){return name+(name.endsWith("이")?"가":"이")}
const reservedTiles=new Set(["g-2-0","g-2-2","g-6-0","g-6-2","g-8-0","g-10-2"]);
const meadowGrid={sourceWidth:941,sourceHeight:1672,sourceRowY:660,sourceRowStep:67,sourceHalfWidth:110,sourceHalfHeight:67};
const meadowScale=Math.max(W/meadowGrid.sourceWidth,H/meadowGrid.sourceHeight);
const meadowOffsetX=(W-meadowGrid.sourceWidth*meadowScale)/2;
const villageTiles=Array.from({length:12},(_,row)=>(row%2?[340,560,780]:[230,450,670]).map((sourceX,col)=>{const id=`g-${row}-${col}`;return{id,x:Math.round(meadowOffsetX+sourceX*meadowScale),y:Math.round((meadowGrid.sourceRowY+row*meadowGrid.sourceRowStep)*meadowScale),kind:reservedTiles.has(id)?"nature":"build"}})).flat();
const buildTiles=villageTiles.filter(tile=>tile.kind==="build");
const entities=[
 {id:"tree-a",type:"tree",tileId:"g-2-0",size:118,hp:3,maxHp:3,reward:{wood:2}},
 {id:"rocks-a",type:"rocks",tileId:"g-2-2",size:93,hp:3,maxHp:3,reward:{stone:2}},
 {id:"logs-a",type:"logs",tileId:"g-6-0",size:92,hp:2,maxHp:2,reward:{wood:2}},
 {id:"grass-a",type:"grass",tileId:"g-6-2",size:82,hp:1,maxHp:1,reward:{sprout:1}},
 {id:"berries-a",type:"berries",tileId:"g-10-2",size:91,hp:2,maxHp:2,reward:{berry:2}},
 {id:"grass-b",type:"grass",tileId:"g-8-0",size:76,hp:1,maxHp:1,reward:{sprout:1}}
];
for(const entity of entities){const tile=villageTiles.find(t=>t.id===entity.tileId);entity.x=tile.x;entity.y=tile.y}
const forestEntities=[
 {id:"forest-tree",type:"tree",x:77,y:391,size:132,hp:3,maxHp:3,reward:{wood:2,resin:1}},
 {id:"forest-rocks",type:"rocks",x:307,y:407,size:102,hp:3,maxHp:3,reward:{stone:2,resin:1}},
 {id:"forest-berries",type:"berries",x:220,y:545,size:104,hp:2,maxHp:2,reward:{berry:2,resin:1}},
 {id:"forest-grass",type:"grass",x:76,y:634,size:91,hp:1,maxHp:1,reward:{sprout:2,resin:1}},
 {id:"forest-logs",type:"logs",x:308,y:660,size:100,hp:2,maxHp:2,reward:{wood:2,resin:1}}
];
const groveEntities=[
 {id:"grove-tree",type:"tree",x:76,y:395,size:125,hp:3,maxHp:3,reward:{wood:2,petal:1}},
 {id:"grove-berries-a",type:"berries",x:312,y:423,size:102,hp:2,maxHp:2,reward:{berry:2,petal:1}},
 {id:"grove-grass",type:"grass",x:80,y:590,size:90,hp:1,maxHp:1,reward:{sprout:2,petal:1}},
 {id:"grove-berries-b",type:"berries",x:289,y:658,size:100,hp:2,maxHp:2,reward:{berry:2,petal:1}},
 {id:"grove-logs",type:"logs",x:208,y:515,size:91,hp:2,maxHp:2,reward:{wood:2,petal:1}}
];
const snowEntities=[
 {id:"snow-rocks-a",type:"rocks",x:76,y:393,size:111,hp:3,maxHp:3,reward:{stone:2,crystal:1}},
 {id:"snow-logs",type:"logs",x:306,y:430,size:100,hp:2,maxHp:2,reward:{wood:2,crystal:1}},
 {id:"snow-grass",type:"grass",x:74,y:604,size:90,hp:1,maxHp:1,reward:{sprout:2,crystal:1}},
 {id:"snow-rocks-b",type:"rocks",x:292,y:660,size:102,hp:3,maxHp:3,reward:{stone:2,crystal:1}},
 {id:"snow-berries",type:"berries",x:199,y:528,size:95,hp:2,maxHp:2,reward:{berry:2,crystal:1}}
];
const regionEntities={village:entities,forest:forestEntities,grove:groveEntities,snow:snowEntities};
const regions={village:{name:"햇살 마을",hint:"서식지와 가구를 만드는 곳"},forest:{name:"햇살 숲",hint:"건축가와 다리를 고치면 열려요"},grove:{name:"꽃바람 숲",hint:"탐험삐약 · 햇살 숲 채집 3곳"},snow:{name:"눈꽃 들판",hint:"풀잎삐약 · 꽃바람 숲 채집 3곳"}};
function activeEntities(){return regionEntities[state.area]||entities}
const chickCatalog=[
 {id:"base",name:"삐약이",asset:"base",status:"첫 둥지를 찾아온 마을의 첫 주민이에요.",skill:"응원: 하루 한 번 기운 3 회복",habitat:"햇살 빈터",clue:"정돈된 초원에 관심이 있어요.",wish:"텃밭이나 모닥불",favorite:["garden","campfire","picnic"],request:{berry:1},ready:()=>state.cleared>=1,missing:()=>`마을 빈터 정리 ${Math.min(state.cleared,1)}/1`},
 {id:"scout",name:"탐험삐약",asset:"scout",status:"새로운 길을 살피는 탐험가예요.",skill:"햇살 숲의 숨은 길을 찾아요",habitat:"텃밭 쉼터",clue:"텃밭 가까운 둥지를 살펴봐요.",wish:"텃밭",favorite:["garden"],request:{wood:2},ready:nest=>state.cleared>=3&&nearFacility(nest,["garden"]),missing:nest=>state.cleared<3?`마을 빈터 정리 ${Math.min(state.cleared,3)}/3`:"둥지 곁 텃밭 필요"},
 {id:"builder",name:"뚝딱삐약",asset:"builder",status:"무거운 자재를 옮기고 다리를 고칠 수 있어요.",skill:"개울 다리 복구",habitat:"나무 작업터",clue:"통나무 더미나 작업대 가까운 곳을 좋아해요.",wish:"작업대",favorite:["workbench"],request:{stone:2},ready:nest=>state.level>=2&&(nearFacility(nest,["workbench"])||nearNature(nest,"logs")),missing:nest=>state.level<2?`환경 Lv.${state.level}/2`:"둥지 곁 통나무 또는 작업대 필요"},
 {id:"leaf",name:"풀잎삐약",asset:"leaf",status:"꽃바람 숲의 식물 돌보기를 좋아해요.",skill:"시든 꽃밭을 되살려 눈꽃 길을 열어요",habitat:"꽃잎 정원",clue:"숲 탐험 뒤 텃밭이나 꽃 아치를 놓아 봐요.",wish:"텃밭이나 꽃 아치",favorite:["garden","arch"],request:{sprout:2},ready:nest=>state.forestCleared>=3&&nearFacility(nest,["garden","arch"]),missing:nest=>state.forestCleared<3?`햇살 숲 채집 ${Math.min(state.forestCleared,3)}/3`:"둥지 곁 텃밭 또는 꽃 아치 필요"},
 {id:"camera",name:"찰칵삐약",asset:"camera",status:"새 지역의 풍경을 기록해요.",skill:"꽃바람 숲의 비밀 풍경을 사진에 담아요",habitat:"사진 쉼터",clue:"꽃바람 숲을 둘러본 뒤 쉬기 좋은 자리를 꾸며요.",wish:"소풍 탁자나 가로등",favorite:["picnic","lamp"],request:{berry:2},ready:nest=>state.groveCleared>=2&&nearFacility(nest,["picnic","lamp"]),missing:nest=>state.groveCleared<2?`꽃바람 숲 채집 ${Math.min(state.groveCleared,2)}/2`:"둥지 곁 소풍 탁자 또는 가로등 필요"},
 {id:"snow",name:"눈송삐약",asset:"snow",status:"눈꽃 들판에서 온 차분한 친구예요.",skill:"얼음 놀이터를 만들어요",habitat:"따뜻한 보금자리",clue:"눈꽃 들판을 살핀 뒤 따뜻하고 밝은 자리를 찾아요.",wish:"모닥불이나 가로등",favorite:["campfire","lamp"],request:{stone:2},ready:nest=>state.snowCleared>=2&&nearFacility(nest,["campfire","lamp"]),missing:nest=>state.snowCleared<2?`눈꽃 들판 채집 ${Math.min(state.snowCleared,2)}/2`:"둥지 곁 모닥불 또는 가로등 필요"}
];
const chicks=[];
const facilities=[];
const recipes={
 nest:{name:"포근한 빈 둥지",asset:"nest",desc:"병아리 한 마리마다 하나씩 필요해요.",cost:{wood:2,sprout:1},size:92,level:1},
 campfire:{name:"포근한 모닥불",asset:"campfire",desc:"쉬면서 기운을 채워요.",cost:{wood:3,stone:2},size:94},
 workbench:{name:"나무 작업대",asset:"workbench",desc:"가끔 나무를 만들어요.",cost:{wood:4,stone:2},size:100},
 garden:{name:"작은 텃밭",asset:"garden",desc:"열매와 새싹을 길러요.",cost:{wood:2,sprout:2},size:106},
 lamp:{name:"마을 가로등",asset:"lamp",desc:"마을의 행복을 밝혀요.",cost:{wood:2,stone:1},size:91},
 picnic:{name:"소풍 탁자",asset:"picnic",desc:"병아리들의 쉬는 자리예요.",price:3,size:105,level:1},
 arch:{name:"꽃 아치",asset:"arch",desc:"꽃길을 꾸며 행복을 더해요.",price:5,size:103,level:2},
 swing:{name:"꽃 그네",asset:"swing",desc:"병아리들과 놀며 행복을 올려요.",price:6,size:108,level:2}
};
recipes.workbench.level=2;recipes.lamp.level=2;recipes.campfire.level=1;recipes.garden.level=1;
function nestCount(){return facilities.filter(f=>f.type==="nest").length}
function nearFacility(nest,types,radius=145){return facilities.some(f=>types.includes(f.type)&&Math.hypot(f.x-nest.x,f.y-nest.y)<=radius)}
function nearNature(nest,type,radius=145){return entities.some(e=>e.type===type&&Math.hypot(e.x-nest.x,e.y-nest.y)<=radius)}
function freeNests(){return facilities.filter(f=>f.type==="nest"&&!f.occupant&&state.guest?.nestId!==f.id)}
function freeNest(){return freeNests()[0]}
function readyCandidates(){if(state.guest)return[];return chickCatalog.filter(info=>!hasChick(info.id)).flatMap(info=>{const nest=freeNests().find(n=>info.ready(n));return nest?[{info,nest}]:[]})}
function leadFor(id){return state.leads[id]||(state.leads[id]={signs:0})}
function encounterChance(){const candidates=readyCandidates();if(!candidates.length)return 0;const mostSigns=Math.max(...candidates.map(candidate=>leadFor(candidate.info.id).signs));if(mostSigns>=(!hasChick("base")?2:3))return 1;return Math.min(.9,(!hasChick("base")?.65:.4)+mostSigns*.15+Math.min(2,candidates.length-1)*.05+(candidates.some(candidate=>candidate.nest.upgraded)?.1:0))}
function visitorReady(){return readyCandidates().length>0}
function addChick(id,restored=false,nestId=null){const info=chickCatalog.find(entry=>entry.id===id);if(!info||chicks.some(chick=>chick.id===id))return;const index=chicks.length,chick={id,name:info.name,asset:info.asset,x:202,y:restored?430:286,size:65,phase:index*1.8,status:info.status,arrivedAt:restored?-100:state.clock,activity:null,activityCount:0};chicks.push(chick);if(!facilities.some(f=>f.type==="nest"&&f.occupant===id)){const nest=facilities.find(f=>f.id===nestId&&f.type==="nest")||freeNest();if(nest)nest.occupant=id}state.selectedChick=id}
function hasChick(id){return chicks.some(chick=>chick.id===id)}
function timeSlot(){return state.dayClock<24?"morning":state.dayClock<54?"afternoon":"evening"}
function activityLabel(chick){const activity=chick.activity;return activity?.status==="travel"?`이동 중 · ${activity.label}`:activity?.label||"마을을 둘러보는 중"}
function pickChickActivity(chick){
 const profile=lifeData[chick.id];if(!profile)return;
 const options=[];
 for(const routine of profile.activities||[]){if(!routine.times.includes(timeSlot()))continue;const places=routine.place==="nest"?facilities.filter(f=>f.type==="nest"&&f.occupant===chick.id):facilities.filter(f=>f.type===routine.place);for(const place of places)if(!chicks.some(other=>other!==chick&&other.activity?.placeId===place.id))options.push({x:place.x+(place.x>195?-30:30),y:place.y+12,label:routine.label,mark:routine.mark,placeId:place.id})}
 const natural=entities.find(e=>e.type===profile.nature?.type&&e.hp>0&&!chicks.some(other=>other!==chick&&other.activity?.placeId===e.id));if(natural)options.push({x:natural.x+(natural.x>195?-43:43),y:natural.y+13,label:profile.nature.label,mark:profile.nature.mark,placeId:natural.id});
 if(!options.length){const nest=facilities.find(f=>f.type==="nest"&&f.occupant===chick.id);options.push({x:nest?.x||195,y:(nest?.y||515)+12,label:"마을 산책",mark:"♪",placeId:nest?.id||null})}
 const choice=options[(chick.activityCount+state.day+chicks.indexOf(chick))%options.length];chick.activityCount++;
 chick.activity={status:"travel",x:Math.max(42,Math.min(348,choice.x)),y:Math.max(310,Math.min(715,choice.y)),label:choice.label,mark:choice.mark,placeId:choice.placeId,until:0};
}
function regionOpen(id){return id==="village"||id==="forest"&&state.bridgeRepaired||id==="grove"&&state.forestTrailFound||id==="snow"&&state.groveBloomed&&state.level>=3}
const load=()=>Promise.all(Object.entries(source).map(([key,src])=>new Promise(resolve=>{const img=new Image();img.onload=()=>{assets[key]=img;resolve()};img.onerror=()=>resolve();img.src=src})));
function resize(){const rect=canvas.getBoundingClientRect();canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);ctx.setTransform(rect.width/W*dpr,0,0,rect.height/H*dpr,0,0);render()}
function drawContain(img,x,y,w,h=w,alpha=1){if(!img)return;const scale=Math.min(w/img.width,h/img.height),dw=img.width*scale,dh=img.height*scale;ctx.save();ctx.globalAlpha=alpha;ctx.drawImage(img,x+(w-dw)/2,y+(h-dh)/2,dw,dh);ctx.restore()}
function drawBackground(){if(!assets.bg){ctx.fillStyle="#dff2a8";ctx.fillRect(0,0,W,H);return}const scale=Math.max(W/assets.bg.width,H/assets.bg.height),dw=assets.bg.width*scale,dh=assets.bg.height*scale;if(state.area==="forest"||state.area==="snow"){ctx.save();ctx.translate(W,H);ctx.rotate(Math.PI);ctx.drawImage(assets.bg,(W-dw)/2,(H-dh)/2,dw,dh);ctx.restore()}else ctx.drawImage(assets.bg,(W-dw)/2,(H-dh)/2,dw,dh);if(state.area==="forest"){ctx.fillStyle="#4a98651d";ctx.fillRect(0,0,W,H);drawContain(assets.tree,-47,192,104);drawContain(assets.tree,340,260,104)}else if(state.area==="grove"){ctx.fillStyle="#f58da929";ctx.fillRect(0,0,W,H);drawContain(assets.arch,7,205,100);drawContain(assets.arch,322,242,95);for(let i=0;i<16;i++){ctx.fillStyle=i%2?"#ffdfe9a0":"#fff2c2b0";ctx.beginPath();ctx.ellipse((i*83+24)%W,285+(i*97)%420,3,5,.5,0,Math.PI*2);ctx.fill()}}else if(state.area==="snow"){ctx.fillStyle="#dff5ff88";ctx.fillRect(0,0,W,H);for(let i=0;i<30;i++){ctx.fillStyle="#ffffff9c";ctx.beginPath();ctx.arc((i*107+19)%W,275+(i*71)%440,i%3+2,0,Math.PI*2);ctx.fill()}}}
function shadowEllipse(x,y,rx,ry,alpha=.18){ctx.save();ctx.fillStyle=`rgba(48,73,42,${alpha})`;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill();ctx.restore()}
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function drawEntity(e){if(e.hp<=0&&e.fade<=0)return;const shake=e.shake>0?Math.sin(state.clock*55)*4:0,alpha=e.fade===undefined?1:Math.max(0,e.fade/.38);shadowEllipse(e.x,e.y+e.size*.28,e.size*.29,e.size*.1,.14*alpha);drawContain(assets[e.type],e.x-e.size/2+shake,e.y-e.size*.68,e.size,e.size,alpha);if(e.hp>0&&e.hp<e.maxHp){const w=43,x=e.x-w/2,y=e.y-e.size*.49;ctx.fillStyle="#fff9e6";roundRect(x-2,y-2,w+4,9,5);ctx.fill();ctx.fillStyle="#e8b9a7";roundRect(x,y,w,5,3);ctx.fill();ctx.fillStyle="#62aa50";roundRect(x,y,w*(e.hp/e.maxHp),5,3);ctx.fill()}}
function drawFacility(f){shadowEllipse(f.x,f.y+f.size*.25,f.size*.28,f.size*.1);drawContain(assets[f.type],f.x-f.size/2,f.y-f.size*.66,f.size,f.size);if(f.upgraded){ctx.fillStyle="#fff6c8";ctx.beginPath();ctx.arc(f.x-f.size*.34,f.y-f.size*.51,11,0,Math.PI*2);ctx.fill();ctx.fillStyle="#d48e24";ctx.font="900 14px sans-serif";ctx.textAlign="center";ctx.fillText("★",f.x-f.size*.34,f.y-f.size*.51+5)}if(f.type==="nest"&&!f.occupant&&!state.buildMode){const ready=readyCandidates().some(candidate=>candidate.nest.id===f.id),guest=state.guest?.nestId===f.id;if(ready||guest){ctx.fillStyle=guest?"#ffad63":"#76bc62";ctx.beginPath();ctx.arc(f.x+31,f.y-46,13,0,Math.PI*2);ctx.fill();ctx.fillStyle="#fff";ctx.font="900 15px sans-serif";ctx.textAlign="center";ctx.fillText(guest?"!":"?",f.x+31,f.y-41)}}if(f.cooldown>state.clock){const remain=Math.ceil(f.cooldown-state.clock);ctx.fillStyle="#fffdf2e8";roundRect(f.x-20,f.y-f.size*.5,40,18,9);ctx.fill();ctx.fillStyle="#596258";ctx.font="900 9px sans-serif";ctx.textAlign="center";ctx.fillText(`${remain}초`,f.x,f.y-f.size*.5+12)}}
function drawBridgeMarker(){ctx.save();const y=222+Math.sin(state.clock*2)*2;ctx.shadowColor="#31462d55";ctx.shadowBlur=9;ctx.fillStyle=state.bridgeRepaired?"#5ca64c":"#d69049";roundRect(245,y-13,99,29,11);ctx.fill();ctx.lineWidth=2;ctx.strokeStyle="#fff7d6";ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle="#fff";ctx.font="900 11px sans-serif";ctx.textAlign="center";ctx.fillText(state.bridgeRepaired?"지역 이동":"다리 수리",294,y+6);if(!state.bridgeRepaired&&state.area==="village"){ctx.fillStyle="#765039";ctx.fillRect(266,162,7,16);ctx.fillRect(305,169,7,15);ctx.strokeStyle="#e0c196";ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(269,171);ctx.lineTo(311,178);ctx.stroke()}ctx.restore()}
function visibleProjects(){if(state.area==="forest")return[{id:"trail",x:195,y:322,label:state.forestTrailFound?"열린 숲길":"수상한 덩굴길",done:state.forestTrailFound,color:"#4b9a58"}];if(state.area==="grove")return[{id:"bloom",x:142,y:316,label:state.groveBloomed?"피어난 꽃밭":"시든 꽃밭",done:state.groveBloomed,color:"#de8caa"},{id:"photo",x:298,y:322,label:state.photoTaken?"사진 명소":"비밀 풍경",done:state.photoTaken,color:"#6f9ebe"}];if(state.area==="snow")return[{id:"ice",x:195,y:316,label:state.icePlayground?"얼음 놀이터":"얼어붙은 빈터",done:state.icePlayground,color:"#7bb8d0"}];return[]}
function drawProjectTerrain(){ctx.save();if(state.area==="forest"){if(state.forestTrailFound){ctx.lineCap="round";ctx.beginPath();ctx.moveTo(174,352);ctx.quadraticCurveTo(238,275,390,276);ctx.strokeStyle="#61a263";ctx.lineWidth=48;ctx.stroke();ctx.strokeStyle="#e8d5a2";ctx.lineWidth=32;ctx.stroke();for(let i=0;i<9;i++){ctx.fillStyle=i%2?"#fff6d1":"#daedab";ctx.beginPath();ctx.arc(186+i*22,338-i*6,3,0,Math.PI*2);ctx.fill()}}else{ctx.strokeStyle="#477852";ctx.lineWidth=7;for(let i=0;i<4;i++){ctx.beginPath();ctx.moveTo(150+i*20,350);ctx.bezierCurveTo(155+i*20,324,178+i*15,307,206+i*12,291);ctx.stroke()}}}else if(state.area==="grove"){ctx.fillStyle=state.groveBloomed?"#86b75f":"#a6a278";ctx.beginPath();ctx.ellipse(142,338,77,34,0,0,Math.PI*2);ctx.fill();for(let i=0;i<17;i++){const x=83+(i*37)%118,y=323+(i*17)%30;ctx.fillStyle=state.groveBloomed?i%2?"#ffd9e8":"#fff0a9":"#776e55";ctx.beginPath();ctx.arc(x,y,state.groveBloomed?4:2,0,Math.PI*2);ctx.fill()}}else if(state.area==="snow"){ctx.fillStyle=state.icePlayground?"#9bdcf2":"#c4dae0";ctx.strokeStyle="#edf9ff";ctx.lineWidth=5;ctx.beginPath();ctx.ellipse(195,340,79,34,0,0,Math.PI*2);ctx.fill();ctx.stroke();if(state.icePlayground){ctx.strokeStyle="#ffffffad";ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(149,345);ctx.quadraticCurveTo(195,320,239,348);ctx.stroke()}}ctx.restore()}
function drawWorldProjects(){for(const project of visibleProjects()){ctx.save();if(project.done){ctx.fillStyle=project.color+"70";ctx.beginPath();ctx.ellipse(project.x,project.y+17,58,24,0,0,Math.PI*2);ctx.fill();for(let i=0;i<7;i++){const x=project.x-44+i*15,y=project.y+10+(i%2)*14;ctx.fillStyle=state.area==="snow"?"#effbff":"#fff2bf";ctx.beginPath();ctx.arc(x,y,3+i%2,0,Math.PI*2);ctx.fill()}}ctx.fillStyle=project.done?project.color:"#6b624c";ctx.strokeStyle="#fff9e3";ctx.lineWidth=2;roundRect(project.x-62,project.y-31,124,31,13);ctx.fill();ctx.stroke();ctx.fillStyle="#fff";ctx.textAlign="center";ctx.font="900 11px sans-serif";ctx.fillText(project.label,project.x,project.y-11);ctx.restore()}}
function projectAt(p){return visibleProjects().find(project=>Math.abs(p.x-project.x)<64&&Math.abs(p.y-project.y+15)<28)}
function useWorldProject(project){if(project.id==="trail"){if(state.forestTrailFound){toast("탐험삐약이 찾아낸 꽃바람 숲길이에요.");return}if(!hasChick("scout")){toast("덩굴 너머에 길이 보여요. 탐험을 좋아하는 친구가 필요해요.");return}if(state.resources.resin<2){toast(`숲의 수지 ${state.resources.resin}/2 · 숲 자연물을 살펴보세요.`);return}state.resources.resin-=2;state.forestTrailFound=true;toast("탐험삐약이 덩굴길을 찾아냈어요! 꽃바람 숲이 열렸습니다.")}else if(project.id==="bloom"){if(state.groveBloomed){toast("풀잎삐약이 되살린 꽃밭이에요.");return}if(!hasChick("leaf")){toast("꽃밭이 시들었어요. 식물을 돌보는 친구가 필요해요.");return}if(state.resources.petal<2){toast(`꽃잎 ${state.resources.petal}/2 · 꽃바람 숲에서 모아 보세요.`);return}state.resources.petal-=2;state.groveBloomed=true;toast("풀잎삐약이 꽃밭을 되살렸어요! 환경 Lv.3에서 눈꽃 길이 열려요.")}else if(project.id==="photo"){if(state.photoTaken){toast("찰칵삐약과 남긴 사진 명소예요.");return}if(!hasChick("camera")){toast("멋진 풍경이에요. 사진을 좋아하는 친구와 다시 와 보세요.");return}state.photoTaken=true;state.acorns+=3;toast("찰칵삐약이 비밀 풍경을 기록했어요! 도토리 3개를 얻었습니다.")}else if(project.id==="ice"){if(state.icePlayground){state.happiness+=2;toast("얼음 놀이터에서 미끄럼을 탔어요. 행복 +2");checkProgress();saveGame();return}if(!hasChick("snow")){toast("얼음을 다룰 줄 아는 친구가 필요해요.");return}if(state.resources.crystal<2){toast(`눈 결정 ${state.resources.crystal}/2 · 눈꽃 들판에서 모아 보세요.`);return}state.resources.crystal-=2;state.icePlayground=true;toast("눈송삐약이 얼음 놀이터를 만들었어요!")}state.dailyCare=true;state.happiness+=5;burst(project.x,project.y,project.color);checkProgress();saveGame()}
function drawChick(c){const active=["act","shared","respond"].includes(c.activity?.status),bob=Math.sin(state.clock*(active?6:3)+c.phase)*(active?4:2.4);shadowEllipse(c.x,c.y+25,c.size*.25,c.size*.08,.16);ctx.save();ctx.shadowColor="#3f52373b";ctx.shadowBlur=6;ctx.shadowOffsetY=3;drawContain(assets[c.asset],c.x-c.size/2,c.y-c.size*.62+bob,c.size,c.size);ctx.restore();if(active){const a=c.activity;ctx.fillStyle=a.status==="shared"?"#ffefc9":"#fffdf2";ctx.strokeStyle="#e8d8b0";ctx.lineWidth=1;roundRect(c.x-28,c.y-60,56,20,10);ctx.fill();ctx.stroke();ctx.fillStyle=a.status==="shared"?"#d77a42":"#5d8350";ctx.font="900 11px sans-serif";ctx.textAlign="center";ctx.fillText(a.mark||"♪",c.x,c.y-46);if(a.status==="shared"){ctx.fillStyle="#ffcc78";ctx.beginPath();ctx.arc(c.x+25+Math.sin(state.clock*5)*5,c.y-30,3,0,Math.PI*2);ctx.fill()}}if(state.clock-c.arrivedAt<5){ctx.fillStyle="#fffdf2";roundRect(c.x-31,c.y-c.size*.68-18,62,18,9);ctx.fill();ctx.fillStyle="#4c6545";ctx.font="900 9px sans-serif";ctx.textAlign="center";ctx.fillText("새 친구!",c.x,c.y-c.size*.68-5)}}
function guestPosition(){const nest=facilities.find(f=>f.id===state.guest?.nestId);return nest?{x:Math.min(345,nest.x+38),y:nest.y+10}:null}
function drawGuest(){if(!state.guest)return;const info=chickCatalog.find(c=>c.id===state.guest.id),p=guestPosition();if(!info||!p)return;shadowEllipse(p.x,p.y+20,20,7);drawContain(assets[info.asset],p.x-37,p.y-46+Math.sin(state.clock*3)*2,74,74);ctx.fillStyle="#fff9e9";roundRect(p.x-31,p.y-59,62,19,9);ctx.fill();ctx.fillStyle="#ad6334";ctx.font="900 10px sans-serif";ctx.textAlign="center";ctx.fillText("새 손님!",p.x,p.y-46)}
function drawLeadSigns(){if(state.area!=="village"||state.guest)return;const marked=new Set();for(const {info,nest} of readyCandidates()){const signs=leadFor(info.id).signs;if(!signs||marked.has(nest.id))continue;marked.add(nest.id);const direction=nest.x>195?-1:1;ctx.save();ctx.fillStyle="#9b7250";for(let i=0;i<Math.min(3,signs+1);i++){const x=nest.x+direction*(44+i*11),y=nest.y+17+i*6;ctx.beginPath();ctx.ellipse(x,y,5,3,-.35,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(x+direction*3,y-5,2,0,Math.PI*2);ctx.fill()}ctx.restore()}}
function tileAt(x,y){const halfWidth=meadowGrid.sourceHalfWidth*meadowScale,halfHeight=meadowGrid.sourceHalfHeight*meadowScale;return villageTiles.map(tile=>({tile,distance:Math.abs(x-tile.x)/halfWidth+Math.abs(y-tile.y)/halfHeight})).filter(entry=>entry.distance<=1).sort((a,b)=>a.distance-b.distance)[0]?.tile}
function tileOccupied(tile){return facilities.some(f=>f.tileId===tile.id)}
function nearestFreeTile(x,y,used=new Set()){return buildTiles.filter(tile=>!used.has(tile.id)&&!tileOccupied(tile)).sort((a,b)=>Math.hypot(a.x-x,a.y-y)-Math.hypot(b.x-x,b.y-y))[0]}
function drawDiamond(tile,fill,stroke,width=1){const halfWidth=meadowGrid.sourceHalfWidth*meadowScale,halfHeight=meadowGrid.sourceHalfHeight*meadowScale;ctx.beginPath();ctx.moveTo(tile.x,tile.y-halfHeight);ctx.lineTo(tile.x+halfWidth,tile.y);ctx.lineTo(tile.x,tile.y+halfHeight);ctx.lineTo(tile.x-halfWidth,tile.y);ctx.closePath();ctx.fillStyle=fill;ctx.fill();ctx.strokeStyle=stroke;ctx.lineWidth=width;ctx.stroke()}
function drawGroundGrid(){if(state.area!=="village")return;ctx.save();for(const tile of villageTiles){const occupied=tile.kind==="build"&&tileOccupied(tile);if(state.buildMode){const active=state.pointer?.id===tile.id;drawDiamond(tile,tile.kind==="nature"?"#dfaa6480":occupied?"#667b7055":active?"#f7f7bdcc":"#dcffb999",tile.kind==="nature"?"#ae753f":occupied?"#829484":active?"#ffffff":"#5caa57",active?3:2)}else if(tile.kind==="nature")drawDiamond(tile,"#e9bb7240","#b48f5d44")}ctx.restore()}
function drawBuildGhost(){if(!state.buildMode||!state.pointer||state.pointer.kind!=="build"||tileOccupied(state.pointer))return;const r=recipes[state.buildMode],x=state.pointer.x,y=state.pointer.y;ctx.save();ctx.globalAlpha=.7;shadowEllipse(x,y+r.size*.25,r.size*.3,r.size*.12,.16);drawContain(assets[r.asset],x-r.size/2,y-r.size*.66,r.size,r.size);ctx.restore()}
function drawEffects(){for(const e of state.effects){const t=e.life/e.max;ctx.save();ctx.globalAlpha=Math.min(1,t*2);ctx.fillStyle=e.color||"#fff";ctx.strokeStyle="#493f2f";ctx.lineWidth=3;ctx.font="900 14px sans-serif";ctx.textAlign="center";ctx.strokeText(e.text,e.x,e.y);ctx.fillText(e.text,e.x,e.y);ctx.restore()}for(const p of state.particles){ctx.save();ctx.globalAlpha=Math.max(0,p.life/.65);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill();ctx.restore()}}
function render(){ctx.clearRect(0,0,W,H);drawBackground();drawGroundGrid();drawProjectTerrain();drawBridgeMarker();const layers=[];activeEntities().filter(e=>e.hp>0||e.fade>0).forEach(e=>layers.push({y:e.y,draw:()=>drawEntity(e)}));if(state.area==="village")facilities.forEach(f=>layers.push({y:f.y,draw:()=>drawFacility(f)}));if(state.area==="village")chicks.forEach(c=>layers.push({y:c.y,draw:()=>drawChick(c)}));if(state.area==="village"&&state.guest)layers.push({y:guestPosition()?.y||0,draw:drawGuest});layers.sort((a,b)=>a.y-b.y).forEach(l=>l.draw());drawLeadSigns();drawWorldProjects();drawBuildGhost();drawEffects()}
function update(dt){
 state.clock+=dt;state.dayClock+=dt;
 for(const e of Object.values(regionEntities).flat()){e.shake=Math.max(0,(e.shake||0)-dt);if(e.hp<=0)e.fade=Math.max(0,(e.fade??.38)-dt)}
 for(const e of state.effects){e.life-=dt;e.y-=22*dt}state.effects=state.effects.filter(e=>e.life>0);
 for(const p of state.particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=55*dt}state.particles=state.particles.filter(p=>p.life>0);
 for(const c of chicks){
  if(!c.activity||(c.activity.status!=="travel"&&state.clock>=c.activity.until))pickChickActivity(c);
  const a=c.activity;if(!a)continue;
  if(a.status==="travel"){
   const dx=a.x-c.x,dy=a.y-c.y,dist=Math.hypot(dx,dy),speed=c.id==="builder"?24:31;
   if(dist<=speed*dt+3){c.x=a.x;c.y=a.y;a.status=a.kind==="call"?"respond":"act";a.until=state.clock+(a.kind==="call"?4:7+(c.activityCount%3)*2)}
   else{c.x+=dx/dist*speed*dt;c.y+=dy/dist*speed*dt}
  }
 }
}
function canvasPoint(event){const r=canvas.getBoundingClientRect();return{x:(event.clientX-r.left)/r.width*W,y:(event.clientY-r.top)/r.height*H}}
function hitEntity(p){return entities.filter(e=>e.hp>0).reverse().find(e=>Math.hypot(p.x-e.x,p.y-(e.y-e.size*.15))<e.size*.43)}
function hitChick(p){return [...chicks].reverse().find(c=>Math.hypot(p.x-c.x,p.y-(c.y-c.size*.18))<c.size*.48)}
function hitFacility(p){return [...facilities].reverse().find(f=>Math.hypot(p.x-f.x,p.y-(f.y-f.size*.15))<f.size*.42)}
function hitWorld(p){const hits=[];for(const e of activeEntities().filter(e=>e.hp>0))if(Math.hypot(p.x-e.x,p.y-(e.y-e.size*.15))<e.size*.43)hits.push({kind:"entity",item:e,y:e.y});if(state.area==="village"){for(const f of facilities)if(Math.hypot(p.x-f.x,p.y-(f.y-f.size*.15))<f.size*.42)hits.push({kind:"facility",item:f,y:f.y});for(const c of chicks)if(Math.hypot(p.x-c.x,p.y-(c.y-c.size*.18))<c.size*.48)hits.push({kind:"chick",item:c,y:c.y});const guest=guestPosition();if(guest&&Math.hypot(p.x-guest.x,p.y-(guest.y-12))<39)hits.push({kind:"guest",item:state.guest,y:guest.y+10})}return hits.sort((a,b)=>b.y-a.y)[0]}
function validPlacement(x,y){const tile=tileAt(x,y);return state.area==="village"&&!!tile&&tile.kind==="build"&&!tileOccupied(tile)}
function burst(x,y,color="#f2c650"){for(let i=0;i<9;i++){const angle=Math.PI*2*i/9+i*.17;state.particles.push({x,y:y-14,vx:Math.cos(angle)*(24+4*i),vy:Math.sin(angle)*(24+4*i)-28,r:2+i%3,life:.65,color})}}
function floatText(x,y,text,color="#fff4a8"){state.effects.push({x,y,text,color,life:.85,max:.85})}
function satisfactionFor(id){const info=chickCatalog.find(c=>c.id===id),nest=facilities.find(f=>f.type==="nest"&&f.occupant===id);return !!info&&!!nest&&nearFacility(nest,info.favorite)}
function satisfactionCount(){return chicks.filter(c=>satisfactionFor(c.id)).length}
function environmentScore(){return chicks.length+satisfactionCount()+chicks.filter(c=>(state.bonds[c.id]||0)>=3).length}
function updateEnvironmentLevel(announce=true){const score=environmentScore(),next=score>=5?3:score>=2?2:1;if(next>state.level){state.level=next;if(announce){toast(next===2?"환경 Lv.2! 작업대와 새 서식지가 열렸어요.":"환경 Lv.3! 꽃밭을 되살리면 눈꽃 길을 열 수 있어요.");burst(195,370,"#ffdc64")}}}
function gainXP(amount){state.xp+=amount}
function gather(e){if(state.energy<=0){toast("기운이 없어요. 다음 날을 시작해 회복해 주세요.");return}state.energy--;e.hp--;e.shake=.22;burst(e.x,e.y-e.size*.15);floatText(e.x,e.y-e.size*.55,"톡!");if(e.hp<=0){state.dailyCare=true;Object.entries(e.reward).forEach(([key,value])=>{state.resources[key]+=value;floatText(e.x,e.y-e.size*.36,`+${value} ${rewardNames[key]}`,"#fff4a8")});const key={village:"cleared",forest:"forestCleared",grove:"groveCleared",snow:"snowCleared"}[state.area];state[key]++;state.dailyCleanup=true;gainXP(3);burst(e.x,e.y-e.size*.12,"#8ecb65");toast(`${Object.entries(e.reward).map(([k,v])=>`${rewardNames[k]} ${v}개`).join(", ")}를 모았어요`);if(state.area==="forest"&&state.resources.resin>=2&&!state.forestTrailFound)toast("숲의 수지가 모였어요. 덩굴길을 살펴보세요.");if(state.area==="grove"&&state.resources.petal>=2&&!state.groveBloomed)toast("꽃잎이 모였어요. 시든 꽃밭을 살펴보세요.")}checkProgress();saveGame()}
function placeFacility(x,y){const tile=tileAt(x,y);if(!tile){toast("격자 칸을 눌러주세요.");return}if(tile.kind==="nature"){toast("갈색 칸은 자연물이 다시 자라는 자리예요.");return}if(state.movingFacility){const moving=facilities.find(f=>f.id===state.movingFacility);if(!moving){cancelBuild();return}const other=facilities.find(f=>f.tileId===tile.id);if(other&&other!==moving){const old=buildTiles.find(t=>t.id===moving.tileId);other.x=old.x;other.y=old.y;other.tileId=old.id}moving.x=tile.x;moving.y=tile.y;moving.tileId=tile.id;cancelBuild();state.dailyCare=true;burst(tile.x,tile.y,"#b9ec8d");toast("시설 위치를 바꿨어요. 재료와 도토리는 쓰지 않았어요.");checkProgress();saveGame();return}if(!validPlacement(x,y)){toast("이미 시설이 있는 칸이에요. 다른 초록 칸을 골라주세요.");return}const type=state.buildMode,r=recipes[type];if(r.price?state.acorns<r.price:!canAfford(r.cost)){cancelBuild();toast(r.price?"도토리가 부족해요.":"재료가 부족해요.");return}if(r.price)state.acorns-=r.price;else Object.entries(r.cost).forEach(([key,value])=>state.resources[key]-=value);facilities.push({id:`${type}-${facilities.length+1}`,type,x:tile.x,y:tile.y,tileId:tile.id,size:r.size,cooldown:0});cancelBuild();state.dailyCare=true;gainXP(type==="nest"||type==="garden"?5:3);burst(tile.x,tile.y,"#ffd45c");floatText(tile.x,tile.y-r.size*.55,"완성!","#fff4a8");toast(`${r.name} 완성!`);checkProgress();saveGame()}
function useFacility(f){const r=recipes[f.type],bonus=f.upgraded?1:0;if(f.type==="nest"){state.selectedNestId=f.id;openSheet("habitat-sheet");return}if(f.cooldown>state.clock){toast(`${r.name}은 잠시 뒤에 다시 이용할 수 있어요.`);return}state.dailyCare=true;if(f.type==="campfire"){state.energy=Math.min(state.maxEnergy,state.energy+3+bonus*2);speak(`모닥불에서 기운을 ${3+bonus*2} 회복했어요!`);f.cooldown=12}else if(f.type==="garden"){state.resources.berry+=1+bonus;state.resources.sprout+=1+bonus;speak(`텃밭에서 열매와 새싹을 ${1+bonus}개씩 수확했어요!`);f.cooldown=15}else if(f.type==="workbench"){state.resources.wood+=1+bonus;speak(`작업대에서 나무 ${1+bonus}개를 다듬었어요!`);f.cooldown=12}else if(f.type==="picnic"){state.energy=Math.min(state.maxEnergy,state.energy+2+bonus);state.happiness+=2+bonus;speak("소풍 탁자에서 쉬며 기운과 행복이 올랐어요!");f.cooldown=13}else if(f.type==="swing"){state.happiness+=4+bonus*2;state.plays++;speak("꽃 그네에서 놀아서 마을 행복이 올랐어요!");f.cooldown=12}else{state.happiness+=(f.type==="arch"?3:2)+bonus*2;speak(f.type==="arch"?"꽃 아치 덕분에 마을이 화사해졌어요!":"불빛을 보고 병아리들이 행복해해요!");f.cooldown=10}burst(f.x,f.y-f.size*.2);checkProgress();saveGame()}
function openFriend(chick=chicks.find(c=>c.id===state.selectedChick)||chicks[0]){
 const empty=!chick;document.getElementById("friend-empty").hidden=!empty;document.getElementById("friend-profile").hidden=empty;document.getElementById("friend-actions").hidden=empty;
 document.getElementById("friend-name").textContent=empty?"아직 빈 마을":chick.name;
 if(chick){
  state.selectedChick=chick.id;document.getElementById("friend-image").src=source[chick.asset];
  const info=chickCatalog.find(entry=>entry.id===chick.id),bond=state.bonds[chick.id]||0;
  document.getElementById("friend-status").innerHTML=`<strong>${activityLabel(chick)}</strong><span class="friend-skill">친밀함 ${bond}/5 · ${bond>=3?"친한 친구":"함께 시간을 보내 보세요"}</span><span class="friend-skill">특기: ${info.skill}</span><span class="friend-skill ${satisfactionFor(chick.id)?"happy":"waiting"}">좋아하는 곳: ${info.wish}</span>`;
  document.getElementById("skill-button-hint").textContent={base:"기운 회복",scout:"숲길 찾기",builder:"다리 복구",leaf:"꽃밭 돌보기",camera:"풍경 촬영",snow:"얼음터 만들기"}[chick.id];
  document.getElementById("join-button-hint").textContent=chick.activity?.status==="act"?chick.activity.label:"함께 시간 보내기";
 }
 document.getElementById("friend-roster").innerHTML=chicks.map(c=>`<button class="${c.id===chick?.id?"active":""}" data-chick="${c.id}"><img src="${source[c.asset]}" alt="">${c.name}</button>`).join("");
 document.querySelectorAll("[data-chick]").forEach(button=>button.onclick=()=>openFriend(chicks.find(c=>c.id===button.dataset.chick)));openSheet("friend-sheet")
}
function useFriendSkill(chick){if(chick.id==="base"){if(state.dailySkills.base){toast("삐약이의 응원은 오늘 이미 받았어요.");return}if(state.energy>=state.maxEnergy){toast("기운이 가득해요. 채집 후에 다시 와 보세요.");return}state.energy=Math.min(state.maxEnergy,state.energy+3);state.dailySkills.base=true;state.dailyCare=true;closeSheets();burst(chick.x,chick.y,"#ffe470");toast("삐약이의 응원으로 기운이 3 회복됐어요.");checkProgress();saveGame();return}if(chick.id==="builder"){if(state.area==="village")openSheet("bridge-sheet");else toast("마을의 개울 다리에서 뚝딱삐약의 특기를 써 보세요.");return}const destination={scout:"forest",leaf:"grove",camera:"grove",snow:"snow"}[chick.id],projectId={scout:"trail",leaf:"bloom",camera:"photo",snow:"ice"}[chick.id];if(state.area!==destination){toast(`${regions[destination].name}의 특별한 장소에서 이 특기를 써 보세요.`);return}closeSheets();useWorldProject(visibleProjects().find(p=>p.id===projectId))}
function friendAction(action){
 const chick=chicks.find(c=>c.id===state.selectedChick);if(!chick)return;
 if(action==="skill"){useFriendSkill(chick);return}
 if(state.area!=="village"){toast("일상 교류는 병아리가 생활하는 마을에서 해 주세요.");return}
 const profile=lifeData[chick.id]||{},bond=state.bonds[chick.id]||0;
 if(action==="call"){
  chick.activity={status:"travel",kind:"call",x:195,y:465,label:"인사",mark:"♪",until:0};
  speak(profile.call?.[bond>=3?1:0]||`${subjectName(chick.name)} 다가와요.`);burst(chick.x,chick.y-25,"#ffe2a1");
 }else if(action==="join"){
  const label=chick.activity?.label||"함께 놀기",mark=chick.activity?.mark||"♪";
  chick.activity={status:"shared",x:chick.x,y:chick.y,label:`함께 ${label}`,mark,until:state.clock+6};
  if(!state.dailyBond[chick.id]){state.dailyBond[chick.id]=true;state.bonds[chick.id]=Math.min(5,bond+1);state.happiness+=2;state.plays++}
  speak(profile.join?.[bond>=3?1:0]||`${chick.name}${chick.name.endsWith("이")?"와":"과"} 함께했어요.`);burst(chick.x,chick.y-24,"#ffcf85");
 }
 state.dailyCare=true;closeSheets();checkProgress();saveGame()
}
function canAfford(cost){return Object.entries(cost).every(([key,value])=>state.resources[key]>=value)}
function costText(cost){return Object.entries(cost).map(([k,v])=>`<span class="${state.resources[k]<v?"missing":""}">${rewardNames[k]} ${state.resources[k]}/${v}</span>`).join("")}
function renderRecipes(){document.querySelectorAll("[data-build-tab]").forEach(button=>button.classList.toggle("active",button.dataset.buildTab===state.buildTab));document.getElementById("shop-note").hidden=state.buildTab!=="shop";document.getElementById("recipe-list").innerHTML=Object.entries(recipes).filter(([,r])=>(r.price?"shop":"craft")===state.buildTab).map(([key,r])=>{const unlocked=state.level>=r.level,affordable=r.price?state.acorns>=r.price:canAfford(r.cost),placed=facilities.some(f=>f.type===key);return `<button class="recipe ${affordable&&unlocked?"affordable":"locked"} ${placed&&key!=="nest"?"placed":""}" data-recipe="${key}"><img src="${source[r.asset]}" alt=""><strong>${r.name}${key==="nest"?` · ${nestCount()}개`:""}</strong><small>${r.desc}</small><span class="recipe-cost">${r.price?`<span class="${affordable?"":"missing"}">도토리 ${state.acorns}/${r.price}</span>`:costText(r.cost)}</span>${unlocked?"":`<span class="lock-label">환경 Lv.${r.level}</span>`}</button>`}).join("");document.querySelectorAll("[data-recipe]").forEach(button=>button.onclick=()=>selectRecipe(button.dataset.recipe));document.getElementById("move-section").hidden=!facilities.length;document.getElementById("move-list").innerHTML=facilities.map((f,index)=>`<button data-move="${f.id}">${recipes[f.type].name} ${index+1}</button>`).join("");document.querySelectorAll("[data-move]").forEach(button=>button.onclick=()=>selectMove(button.dataset.move));document.getElementById("upgrade-list").innerHTML=facilities.map((f,index)=>`<button data-upgrade="${f.id}" ${f.upgraded?"disabled":""}>${recipes[f.type].name} ${index+1} · ${f.upgraded?"개선 완료":"도토리 4개로 개선"}<small>${upgradeBenefit(f.type)}</small></button>`).join("");document.querySelectorAll("[data-upgrade]").forEach(button=>button.onclick=()=>upgradeFacility(button.dataset.upgrade))}
function upgradeFacility(id){const facility=facilities.find(f=>f.id===id);if(!facility||facility.upgraded)return;if(state.area!=="village"){toast("마을에 돌아가서 시설을 개선해 주세요.");return}if(state.acorns<4){toast("시설 개선에 도토리 4개가 필요해요.");return}state.acorns-=4;facility.upgraded=true;burst(facility.x,facility.y-28,"#ffe177");toast(`${recipes[facility.type].name} 개선 완료! ${upgradeBenefit(facility.type)}`);checkProgress();saveGame()}
function upgradeBenefit(type){return {nest:"방문 확률 +10%",garden:"열매·새싹 수확량 +1",workbench:"나무 수확량 +1",campfire:"기운 회복 +2",picnic:"기운·행복 추가",swing:"행복 +2",arch:"행복 +2",lamp:"행복 +2"}[type]||"효과 증가"}
function selectRecipe(type){const r=recipes[type];if(state.area!=="village"){toast("시설은 마을에서 놓을 수 있어요. 지역 표지로 돌아가세요.");return}if(state.level<r.level){toast(`환경 레벨 ${r.level}에서 열려요.`);return}if(type==="nest"&&nestCount()>=chickCatalog.length){toast("현재 방문할 수 있는 병아리의 둥지는 모두 준비했어요.");return}if(r.price?state.acorns<r.price:!canAfford(r.cost)){toast(r.price?"도토리가 부족해요. 발견 목표를 이루거나 이미 놓은 시설을 개선하기 전에 아껴 보세요.":"부족한 재료를 확인하고 마을에서 모아주세요.");return}if(!nearestFreeTile(205,505)){toast("설치할 빈 칸이 없어요.");return}closeSheets();state.buildMode=type;state.pointer=nearestFreeTile(205,505);document.getElementById("mode-title").textContent=`${r.name} 놓기`;document.getElementById("mode-banner").hidden=false;toast("초록 칸을 눌러 설치하세요. 갈색 칸은 채집 구역이에요.")}
function selectMove(id){const f=facilities.find(item=>item.id===id);if(!f||state.area!=="village")return;closeSheets();state.movingFacility=id;state.buildMode=f.type;state.pointer=buildTiles.find(tile=>tile.id===f.tileId);document.getElementById("mode-title").textContent=`${recipes[f.type].name} 옮기기`;document.getElementById("mode-banner").hidden=false;toast("옮길 칸을 누르세요. 이미 놓인 시설과 위치를 바꿀 수도 있어요.")}
function cancelBuild(){state.buildMode=null;state.movingFacility=null;state.pointer=null;document.getElementById("mode-banner").hidden=true}
function hasNest(){return nestCount()>0}
function selectedHabitatNest(){return freeNests().find(f=>f.id===state.selectedNestId)||freeNest()}
function habitatConditions(){const nest=selectedHabitatNest();return[{name:"빈 둥지",detail:"친구마다 하나씩 필요해요",done:!!nest},{name:"오늘의 돌봄",detail:"자연을 정리하거나 시설을 이용해요",done:state.dailyCare}]}
function conditionHTML(rows){return rows.map(row=>`<div class="condition-row ${row.done?"done":""}"><i>${row.done?"✓":"·"}</i><span>${row.name}</span><b>${row.done?"충족":row.detail}</b></div>`).join("")}
function knownChick(info){return info.id==="base"||info.id==="scout"&&(hasChick("base")||state.cleared>=2)||info.id==="builder"&&state.level>=2||info.id==="leaf"&&state.bridgeRepaired||info.id==="camera"&&(state.forestTrailFound||state.groveCleared>0)||info.id==="snow"&&(state.groveBloomed||state.snowCleared>0)}
function renderHabitat(){
 const nest=selectedHabitatNest(),guest=state.guest,unmet=chickCatalog.filter(info=>!hasChick(info.id)&&guest?.id!==info.id&&knownChick(info));
 document.getElementById("habitat-copy").textContent=guest?"새 손님이 찾아왔어요. 마을에서 만나 보세요.":nest?"서식지에 남은 흔적을 관찰하고 하루씩 돌봐 주세요.":"빈 둥지를 놓고 자연을 정리해 보세요.";
 document.getElementById("habitat-conditions").innerHTML=conditionHTML(habitatConditions());
 document.getElementById("habitat-candidates").innerHTML=unmet.map(info=>{const ready=!!nest&&info.ready(nest),signs=leadFor(info.id).signs;return `<article class="habitat-candidate ${ready?"ready":""}"><img src="${source[info.asset]}" alt=""><span><strong>${signs?"발자국이 남은 서식지":ready?"새 친구의 기척":info.habitat}</strong><small>${signs?lifeData[info.id]?.sign||info.clue:info.clue}</small><em>${ready?signs?"이곳을 다시 찾아올 것 같아요":"오늘 돌보면 누군가 관심을 보일 거예요":"환경을 더 살펴보세요"}</em></span></article>`}).join("");
 document.getElementById("habitat-note").textContent=guest?"먼저 손님에게 인사해 보세요. 마음을 열면 부탁을 알려줘요.":visitorReady()?state.dailyCare?"오늘 돌봤어요. 다음 날 둥지 주변을 확인해 보세요.":"친구의 기척이 있어요. 오늘 서식지를 돌봐 주세요.":unmet.length?"새로운 자연물이나 가구를 둥지 가까이 놓아 보세요.":"아직 알려진 흔적이 없어요. 마을을 탐험해 보세요.";
 if(!guest&&readyCandidates().some(({info})=>leadFor(info.id).signs>0))document.getElementById("habitat-status").textContent="발자국 발견"
}
function bridgeConditions(){return[{name:"건축가 병아리",detail:"나무 작업터 서식지에서 발견",done:hasChick("builder")},{name:"나무 2개",detail:`보유 ${state.resources.wood}/2`,done:state.resources.wood>=2},{name:"돌 2개",detail:`보유 ${state.resources.stone}/2`,done:state.resources.stone>=2}]}
function renderBridge(){document.getElementById("bridge-conditions").innerHTML=conditionHTML(bridgeConditions());const button=document.getElementById("repair-button");button.disabled=state.bridgeRepaired||!bridgeConditions().every(c=>c.done);button.textContent=state.bridgeRepaired?"복구 완료 · 숲길이 열렸어요":"다리 복구하기"}
function questData(){return[
 {name:"첫 둥지 만들기",desc:"빈 둥지가 있어야 첫 병아리가 와요.",current:Math.min(nestCount(),1),goal:1},
 {name:"첫 병아리 맞이하기",desc:"햇살 빈터를 만들고 찾아온 손님과 친해지세요.",current:Math.min(chicks.length,1),goal:1},
 {name:"주민 세 마리 맞이하기",desc:"서로 다른 서식지를 꾸미고 손님을 맞이하세요.",current:Math.min(chicks.length,3),goal:3},
 {name:"건축가와 다리 복구",desc:"나무 작업터의 친구와 다리를 복구하세요.",current:state.bridgeRepaired?1:0,goal:1},
 {name:"숨은 숲길 찾기",desc:"탐험삐약과 숲의 수지로 덩굴길을 살펴보세요.",current:state.forestTrailFound?1:0,goal:1},
 {name:"꽃밭 되살리기",desc:"풀잎삐약과 꽃잎으로 시든 꽃밭을 돌보세요.",current:state.groveBloomed?1:0,goal:1},
 {name:"얼음 놀이터 만들기",desc:"눈송삐약과 눈 결정으로 새 놀이 공간을 만드세요.",current:state.icePlayground?1:0,goal:1},
 {name:"병아리 여섯 마리 맞이하기",desc:"둥지를 늘려 주민을 한 마리씩 모으세요.",current:Math.min(chicks.length,6),goal:6}
]}
function renderQuests(){const quests=questData(),visible=quests.map((q,i)=>({...q,index:i})).filter(q=>q.current<q.goal).slice(0,1),done=quests.filter(q=>q.current>=q.goal).length;document.getElementById("quest-list").innerHTML=visible.map(q=>`<article class="quest-row"><i>✦</i><span><strong>${q.name}</strong><small>${q.desc}</small></span><b>${q.current}/${q.goal}<small>도토리 +2</small></b></article>`).join("")||'<p class="sheet-copy">마을의 현재 목표를 모두 이루었어요.</p>';document.getElementById("quest-total").textContent=`✓${done}`;document.getElementById("quest-summary").textContent=visible[0]?.name||"마을 탐험 완료!";document.querySelector(".quest-reward strong").textContent="새로운 친구와 길을 발견해 보세요"}
function grantQuestRewards(){questData().forEach((quest,index)=>{if(quest.current>=quest.goal&&!state.claimedQuests.includes(index)){state.claimedQuests.push(index);state.acorns+=2;toast(`${quest.name} 완료 · 도토리 2개를 받았어요.`)}})}
function checkProgress(){const wasPending=state.visitorPending;updateEnvironmentLevel();state.visitorPending=visitorReady();grantQuestRewards();if(state.visitorPending&&!wasPending)toast("새 서식지에 친구가 찾아올 기척이 있어요. 하루를 돌봐 주세요.");syncUI()}
function randomUnit(){state.rngSeed=(Math.imul(1664525,state.rngSeed)+1013904223)>>>0;return state.rngSeed/4294967296}
function rollEncounter(){
 if(state.guest)return"손님이 머물고 있어요. 마을에서 만나 보세요.";
 const candidates=readyCandidates();
 if(!candidates.length)return"새 손님을 위한 서식지 조합이 아직 없어요.";
 if(!state.dailyCare)return"오늘은 서식지를 돌보지 않았어요. 채집하거나 시설을 이용해 주세요.";
 if(randomUnit()<encounterChance()){
  const weights=candidates.map(candidate=>1+leadFor(candidate.info.id).signs),total=weights.reduce((a,b)=>a+b,0);
  let choice=randomUnit()*total,index=0;while(index<weights.length-1&&choice>=weights[index])choice-=weights[index++];
  const pick=candidates[index];state.guest={id:pick.info.id,nestId:pick.nest.id,arrivedDay:state.day+1,phase:"greet"};
  state.encounterMisses=0;burst(pick.nest.x,pick.nest.y-40,"#ffda84");
  return`${subjectName(pick.info.name)} ${pick.info.habitat}에 찾아왔어요! 먼저 다가가 인사해 보세요.`;
 }
 for(const candidate of candidates)leadFor(candidate.info.id).signs=Math.min(3,leadFor(candidate.info.id).signs+1);
 state.encounterMisses++;
 return"서식지에 새로운 발자국이 남았어요. 다음 방문 기회가 높아졌습니다.";
}
function nextDay(){const encounter=rollEncounter();state.day++;state.dayClock=0;state.energy=state.maxEnergy;state.dailyCleanup=false;state.dailyCare=false;state.dailySkills={};state.dailyBond={};state.lastEncounter=encounter;for(const e of Object.values(regionEntities).flat()){e.hp=e.maxHp;e.fade=undefined;e.shake=0}for(const f of facilities)f.cooldown=0;toast(`DAY ${state.day} · ${encounter}`);checkProgress();saveGame()}
function openGuest(){if(!state.guest)return;const info=chickCatalog.find(c=>c.id===state.guest.id),greeting=state.guest.phase==="greet";document.getElementById("guest-name").textContent=info.name;document.getElementById("guest-image").src=source[info.asset];document.getElementById("guest-copy").textContent=greeting?lifeData[info.id]?.greeting||`${subjectName(info.name)} 둥지에서 기다려요.`:`${subjectName(info.name)} 이곳에 머물고 싶어 해요. 작은 부탁을 들어주세요.`;document.getElementById("guest-request-box").hidden=greeting;document.getElementById("guest-request").innerHTML=costText(info.request);const button=document.getElementById("guest-welcome-button");button.disabled=!greeting&&!canAfford(info.request);button.textContent=greeting?"다가가 인사하기":canAfford(info.request)?"부탁을 들어주고 함께 살기":"재료를 모아 다시 만나기";openSheet("guest-sheet")}
function welcomeGuest(){if(!state.guest)return;const info=chickCatalog.find(c=>c.id===state.guest.id);if(state.guest.phase==="greet"){state.guest.phase="request";state.dailyCare=true;toast(`${subjectName(info.name)} 마음을 열었어요. 부탁을 살펴보세요.`);openGuest();saveGame();return}if(!canAfford(info.request)){openGuest();return}Object.entries(info.request).forEach(([key,value])=>state.resources[key]-=value);const nestId=state.guest.nestId;state.guest=null;addChick(info.id,false,nestId);state.bonds[info.id]=1;state.happiness+=5;gainXP(5);state.dailyCare=true;closeSheets();const nest=facilities.find(f=>f.id===nestId);burst(nest?.x||202,nest?.y||430,"#ffd85b");toast(`${subjectName(info.name)} 주민이 되었어요! 이제 마을에서 생활해요.`);checkProgress();saveGame()}
function repairBridge(){if(state.bridgeRepaired)return;if(!bridgeConditions().every(c=>c.done)){renderBridge();toast("건축가와 나무 2개, 돌 2개가 필요해요.");return}state.resources.wood-=2;state.resources.stone-=2;state.bridgeRepaired=true;state.happiness+=20;gainXP(10);closeSheets();burst(294,210,"#ffdf79");toast("다리 복구 완료! 표지를 눌러 숲으로 가보세요.");checkProgress();saveGame()}
function renderRegions(){const visible=Object.entries(regions).filter(([id])=>id==="village"||id==="forest"||id==="grove"&&state.bridgeRepaired||id==="snow"&&state.forestTrailFound);document.getElementById("region-list").innerHTML=visible.map(([id,region])=>`<button data-region="${id}" class="${state.area===id?"current":""}" ${regionOpen(id)?"":"disabled"}><strong>${regionOpen(id)?"↗":"●"} ${region.name}${state.area===id?" · 현재 지역":""}</strong><small>${regionOpen(id)?id==="village"?"둥지와 가구를 놓는 곳":id==="forest"?"숲의 수지 · 수상한 덩굴길":id==="grove"?"꽃잎 · 시든 꽃밭":"눈 결정 · 얼어붙은 빈터":id==="forest"?"다리 복구 후 발견":id==="grove"?"숲의 숨은 길을 찾아보세요":"꽃밭을 되살리고 환경 Lv.3 달성"}</small></button>`).join("");document.querySelectorAll("[data-region]").forEach(button=>button.onclick=()=>goToRegion(button.dataset.region))}
function goToRegion(id){if(!regionOpen(id)){toast(`${regions[id].name}은 아직 열리지 않았어요.`);return}state.area=id;cancelBuild();closeSheets();document.getElementById("area-name").textContent=regions[id].name;toast(`${regions[id].name}에 도착했어요.`);saveGame()}
function travel(){if(!state.bridgeRepaired){openSheet("bridge-sheet");return}renderRegions();openSheet("region-sheet")}
function renderBag(){const items=[{k:"wood",icon:"◆"},{k:"stone",icon:"●"},{k:"sprout",icon:"♣"},{k:"berry",icon:"●"},{k:"resin",icon:"✦"},{k:"petal",icon:"✿"},{k:"crystal",icon:"◇"}];document.getElementById("bag-grid").innerHTML=items.map(i=>`<article class="bag-item"><b class="${i.k}">${i.icon}</b><strong>${state.resources[i.k]}</strong><small>${rewardNames[i.k]}</small></article>`).join("")}
function syncUI(){for(const key of["wood","stone","sprout","berry"])document.getElementById(`${key}-count`).textContent=state.resources[key];document.getElementById("energy-count").textContent=state.energy;document.getElementById("happiness-count").textContent=state.happiness;document.getElementById("acorn-count").textContent=state.acorns;document.getElementById("bag-acorn-count").textContent=state.acorns;document.getElementById("day-count").textContent=state.day;document.getElementById("friends-count").textContent=`친구 ${chicks.length}`;document.getElementById("level-count").textContent=state.level;document.getElementById("satisfaction-count").textContent=`${satisfactionCount()}/${chicks.length}`;const score=environmentScore(),start=state.level===1?0:state.level===2?2:5,end=state.level===1?2:5;document.getElementById("level-progress").style.width=state.level===3?"100%":`${Math.min(100,Math.max(0,(score-start)/(end-start)*100))}%`;const status=document.getElementById("habitat-status");status.textContent=state.guest?"새 손님 도착":visitorReady()?"새 친구의 기척":nestCount()?"새 흔적을 찾아보세요":"빈 둥지 준비";document.getElementById("habitat-button").classList.toggle("guest",!!state.guest);renderQuests();renderHabitat();renderBridge();renderBag();renderRecipes()}
function openSheet(id){closeSheets();if(id==="build-sheet")renderRecipes();if(id==="quest-sheet")renderQuests();if(id==="bag-sheet")renderBag();if(id==="habitat-sheet")renderHabitat();if(id==="bridge-sheet")renderBridge();if(id==="region-sheet")renderRegions();document.getElementById(id).hidden=false}
function closeSheets(){document.querySelectorAll(".bottom-sheet").forEach(sheet=>sheet.hidden=true)}
function toast(message){const el=document.getElementById("toast");el.textContent=message;el.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove("show"),1900)}
function speak(message){const el=document.getElementById("speech-bubble");el.textContent=message;el.classList.add("show");clearTimeout(speak.timer);speak.timer=setTimeout(()=>el.classList.remove("show"),1900)}
function onCanvas(event){if(state.intro)return;const p=canvasPoint(event);if(state.buildMode){placeFacility(p.x,p.y);return}if(p.x>=242&&p.x<=346&&p.y>=197&&p.y<=252){travel();return}const project=projectAt(p);if(project){useWorldProject(project);return}const hit=hitWorld(p);if(!hit){speak("자연물을 채집하거나 빈 둥지를 지어 첫 병아리를 맞이해 보세요.");return}if(hit.kind==="guest")openGuest();else if(hit.kind==="chick")openFriend(hit.item);else if(hit.kind==="facility")useFacility(hit.item);else gather(hit.item)}
canvas.addEventListener("pointerdown",event=>{event.preventDefault();onCanvas(event)});canvas.addEventListener("pointermove",event=>{if(state.buildMode){const p=canvasPoint(event);state.pointer=tileAt(p.x,p.y)||null;render()}});
document.getElementById("start-game").onclick=()=>{state.intro=false;document.getElementById("intro-card").hidden=true;toast("첫 병아리는 아직 없어요. 빈 둥지를 준비해 주세요.");saveGame()};
document.getElementById("build-button").onclick=()=>openSheet("build-sheet");document.getElementById("bag-button").onclick=()=>openSheet("bag-sheet");document.getElementById("friends-button").onclick=()=>openFriend();document.getElementById("quest-button").onclick=()=>openSheet("quest-sheet");document.getElementById("habitat-button").onclick=()=>state.guest?openGuest():openSheet("habitat-sheet");document.getElementById("guest-welcome-button").onclick=welcomeGuest;document.getElementById("cancel-build").onclick=cancelBuild;
document.querySelectorAll("[data-build-tab]").forEach(button=>button.onclick=()=>{state.buildTab=button.dataset.buildTab;renderRecipes()});
document.getElementById("day-button").onclick=nextDay;document.getElementById("level-button").onclick=()=>toast(state.level===3?"환경 Lv.3 · 꽃밭을 되살리면 눈꽃 길이 열려요.":state.level===2?`환경 점수 ${environmentScore()}/5 · 친한 친구도 점수를 보태요.`:`환경 점수 ${environmentScore()}/2 · 좋아하는 가구나 친밀함으로 성장해요.`);document.getElementById("repair-button").onclick=repairBridge;
document.getElementById("restart-button").onclick=event=>{const button=event.currentTarget;if(!button.classList.contains("armed")){button.classList.add("armed");button.textContent="진행 기록 삭제 · 한 번 더 누르기";clearTimeout(button.resetTimer);button.resetTimer=setTimeout(()=>{button.classList.remove("armed");button.textContent="처음부터 새로 시작"},5000);return}state.discardingSave=true;localStorage.removeItem("chick-village-save-v2");location.reload()};
document.addEventListener("visibilitychange",()=>{if(document.hidden&&!state.intro&&!state.discardingSave)saveGame()});addEventListener("pagehide",()=>{if(!state.intro&&!state.discardingSave)saveGame()});
document.querySelectorAll("[data-close]").forEach(button=>button.onclick=()=>document.getElementById(button.dataset.close).hidden=true);document.querySelectorAll("[data-friend-action]").forEach(button=>button.onclick=()=>friendAction(button.dataset.friendAction));
document.addEventListener("keydown",event=>{if(event.key==="Escape"){closeSheets();cancelBuild()}});addEventListener("resize",resize);
window.advanceTime=ms=>{for(let i=0,n=Math.max(1,Math.round(ms/(1000/60)));i<n;i++)update(1/60);render()};
window.render_game_to_text=()=>JSON.stringify({
 coordinate_system:"portrait canvas 390x844; origin top-left",mode:state.intro?"intro":state.buildMode?`placing ${state.buildMode}`:"explore",area:state.area,
 day:state.day,timeSlot:timeSlot(),energy:`${state.energy}/${state.maxEnergy}`,resources:state.resources,acorns:state.acorns,dailyCare:state.dailyCare,dailySkills:state.dailySkills,happiness:state.happiness,
 regions:Object.keys(regions).map(id=>({id,open:regionOpen(id)})),environment:{level:state.level,score:environmentScore(),satisfied:satisfactionCount(),closeFriends:chicks.filter(c=>(state.bonds[c.id]||0)>=3).length},
 projects:{forestTrailFound:state.forestTrailFound,groveBloomed:state.groveBloomed,icePlayground:state.icePlayground,photoTaken:state.photoTaken,visible:visibleProjects()},
 habitat:{nests:nestCount(),residents:chicks.length,candidates:readyCandidates().map(({info,nest})=>({id:info.id,nestId:nest.id,signs:leadFor(info.id).signs})),chance:encounterChance(),guest:state.guest,lastEncounter:state.lastEncounter},
 bridge:{repaired:state.bridgeRepaired,conditions:bridgeConditions()},quests:questData().map((q,index)=>({...q,rewarded:state.claimedQuests.includes(index)})),
 obstacles:activeEntities().filter(e=>e.hp>0).map(e=>({id:e.id,type:e.type,x:Math.round(e.x),y:Math.round(e.y),hp:`${e.hp}/${e.maxHp}`})),
 grid:state.area==="village"?{buildable:buildTiles.length,available:buildTiles.filter(tile=>!tileOccupied(tile)).length,nature:villageTiles.filter(tile=>tile.kind==="nature").map(tile=>({id:tile.id,x:tile.x,y:tile.y})),selected:state.pointer?.id||null}:null,
 facilities:state.area==="village"?facilities.map(f=>({id:f.id,type:f.type,tileId:f.tileId,occupant:f.occupant||null,upgraded:!!f.upgraded,x:Math.round(f.x),y:Math.round(f.y),ready:f.cooldown<=state.clock})):[],
 chicks:state.area==="village"?chicks.map(c=>({id:c.id,name:c.name,x:Math.round(c.x),y:Math.round(c.y),activity:c.activity?.status||"idle",doing:activityLabel(c),destination:c.activity?{x:c.activity.x,y:c.activity.y}:null,bond:state.bonds[c.id]||0,joinedToday:!!state.dailyBond[c.id]})):[]
});
function saveGame(){try{localStorage.setItem("chick-village-save-v2",JSON.stringify({schema:8,profileId:state.profileId,day:state.day,dayClock:state.dayClock,area:state.area,energy:state.energy,resources:state.resources,acorns:state.acorns,claimedQuests:state.claimedQuests,dailyCleanup:state.dailyCleanup,dailyCare:state.dailyCare,dailySkills:state.dailySkills,dailyBond:state.dailyBond,bonds:state.bonds,leads:state.leads,encounterMisses:state.encounterMisses,rngSeed:state.rngSeed,guest:state.guest,lastEncounter:state.lastEncounter,cleared:state.cleared,forestCleared:state.forestCleared,groveCleared:state.groveCleared,snowCleared:state.snowCleared,plays:state.plays,happiness:state.happiness,xp:state.xp,level:state.level,bridgeRepaired:state.bridgeRepaired,forestTrailFound:state.forestTrailFound,groveBloomed:state.groveBloomed,icePlayground:state.icePlayground,photoTaken:state.photoTaken,chickIds:chicks.map(c=>c.id),chickStates:chicks.map(c=>({id:c.id,x:c.x,y:c.y,activityCount:c.activityCount})),facilities:facilities.map(({id,type,tileId,x,y,size,occupant,upgraded})=>({id,type,tileId,x,y,size,occupant,upgraded})),obstacles:Object.values(regionEntities).flat().map(({id,hp})=>({id,hp}))}))}catch{}}
function restoreGame(){try{
 const raw=localStorage.getItem("chick-village-save-v2");if(!raw)return;const saved=JSON.parse(raw);
 for(const key of["day","area","energy","cleared","forestCleared","groveCleared","snowCleared","plays","happiness","xp","level","bridgeRepaired"])if(saved[key]!==undefined)state[key]=saved[key];
 state.dayClock=Number.isFinite(saved.dayClock)?Math.max(0,saved.dayClock):0;
 state.profileId=saved.profileId||state.profileId;state.acorns=Number.isFinite(saved.acorns)?Math.max(0,saved.acorns):0;
 state.dailyCleanup=!!saved.dailyCleanup;state.dailyCare=!!saved.dailyCare||(saved.schema<5&&!!saved.dailyCleanup);
 state.dailySkills=saved.dailySkills&&typeof saved.dailySkills==="object"?saved.dailySkills:{};
 state.dailyBond=saved.dailyBond&&typeof saved.dailyBond==="object"?saved.dailyBond:{};
 state.bonds=saved.bonds&&typeof saved.bonds==="object"?saved.bonds:{};
 state.leads=saved.leads&&typeof saved.leads==="object"?saved.leads:{};
 state.encounterMisses=Number.isInteger(saved.encounterMisses)?Math.max(0,saved.encounterMisses):0;
 state.rngSeed=Number.isInteger(saved.rngSeed)?saved.rngSeed>>>0:state.rngSeed;
 state.lastEncounter=typeof saved.lastEncounter==="string"?saved.lastEncounter:"";
 for(const key of Object.keys(state.resources))if(Number.isFinite(saved.resources?.[key]))state.resources[key]=saved.resources[key];
 for(const data of saved.obstacles||[]){const target=Object.values(regionEntities).flat().find(e=>e.id===data.id);if(target){target.hp=data.hp;target.fade=data.hp<=0?0:undefined}}
 const used=new Set();for(const data of saved.facilities||[]){if(!recipes[data.type])continue;let tile=buildTiles.find(t=>t.id===data.tileId&&!used.has(t.id));if(!tile)tile=nearestFreeTile(Number(data.x)||205,Number(data.y)||505,used);if(!tile)continue;used.add(tile.id);facilities.push({...data,x:tile.x,y:tile.y,tileId:tile.id,size:recipes[data.type].size,cooldown:0})}
 const ids=Array.isArray(saved.chickIds)?saved.chickIds:(saved.visitorArrived?["base","scout","builder"]:[]);
 for(const id of ids){if(!facilities.some(f=>f.type==="nest"&&!f.occupant)&&!facilities.some(f=>f.type==="nest"&&f.occupant===id)){const tile=nearestFreeTile(205,505,used);if(tile){used.add(tile.id);facilities.push({id:`nest-migrated-${id}`,type:"nest",x:tile.x,y:tile.y,tileId:tile.id,size:recipes.nest.size,cooldown:0})}}addChick(id,true)}
 for(const data of saved.chickStates||[]){const chick=chicks.find(c=>c.id===data.id);if(chick){if(Number.isFinite(data.x))chick.x=Math.max(35,Math.min(355,data.x));if(Number.isFinite(data.y))chick.y=Math.max(300,Math.min(730,data.y));chick.activityCount=Number.isInteger(data.activityCount)?Math.max(0,data.activityCount):0}}
 state.forestTrailFound=!!saved.forestTrailFound||(saved.schema<7&&hasChick("scout")&&state.forestCleared>=3);
 state.groveBloomed=!!saved.groveBloomed||(saved.schema<7&&hasChick("leaf")&&state.groveCleared>=3);
 state.icePlayground=!!saved.icePlayground;state.photoTaken=!!saved.photoTaken;
 if(saved.guest&&chickCatalog.some(c=>c.id===saved.guest.id)&&facilities.some(f=>f.id===saved.guest.nestId&&f.type==="nest"&&!f.occupant))state.guest={id:saved.guest.id,nestId:saved.guest.nestId,arrivedDay:Number(saved.guest.arrivedDay)||state.day,phase:saved.guest.phase||"request"};
 if(saved.schema<8&&!state.guest)for(const candidate of readyCandidates())leadFor(candidate.info.id).signs=Math.min(3,state.encounterMisses);
 state.claimedQuests=Array.isArray(saved.claimedQuests)?saved.claimedQuests.filter(id=>Number.isInteger(id)&&id>=0&&id<questData().length):questData().flatMap((q,index)=>q.current>=q.goal?[index]:[]);
 if(!Number.isFinite(saved.acorns)&&saved.schema<4)state.acorns=state.claimedQuests.length*2;
 if(!regions[state.area]||!regionOpen(state.area))state.area="village";
 state.visitorPending=visitorReady();state.intro=false;document.getElementById("intro-card").hidden=true;document.getElementById("area-name").textContent=regions[state.area].name
}catch{}}
state.profileId=globalThis.crypto?.randomUUID?.()||`local-${Date.now()}`;restoreGame();load().then(()=>{resize();syncUI()});let previous=performance.now();function loop(now){update(Math.min(.034,(now-previous)/1000));previous=now;render();requestAnimationFrame(loop)}requestAnimationFrame(loop);
})();
