import { chromium } from 'file:///C:/Users/Soyoon%20Bang/.codex/node_modules/playwright/index.mjs';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',e=>{if(e.type()==='error')errors.push(e.text())});
await page.goto('http://localhost:5173');
await page.evaluate(()=>localStorage.removeItem('chick-village-story-v1'));await page.reload();
const state=async()=>JSON.parse(await page.evaluate(()=>window.render_game_to_text()));
const clickNode=async id=>{await page.locator(`[data-node="${id}"]`).click();};
const clickWorld=async(x,y)=>{let p=await page.evaluate(([x,y])=>{let svg=document.querySelector('svg'),pt=svg.createSVGPoint();pt.x=x;pt.y=y;let a=pt.matrixTransform(svg.getScreenCTM());return{x:a.x,y:a.y}},[x,y]);await page.mouse.click(p.x,p.y)};
await clickNode('wood1');await clickNode('wood2');await clickNode('stone1');
await page.locator('[data-panel="craft"]').click();await page.locator('[data-craft="swing"]').click();await page.evaluate(()=>window.advanceTime(11000));
await page.locator('#sheet-close').click();await page.locator('[data-panel="storage"]').click();await page.locator('[data-place="swing"]').click();await page.locator('#place-done').click();
console.log('swing',JSON.stringify((await state()).placements.home));
await page.evaluate(()=>window.advanceTime(151000));await clickNode('wood1');await clickNode('wood2');await clickNode('stone1');
await page.locator('[data-panel="craft"]').click();await page.locator('[data-craft="bench"]').click();await page.evaluate(()=>window.advanceTime(11000));await page.locator('#sheet-close').click();await page.locator('[data-panel="storage"]').click();await page.locator('[data-place="bench"]').click();
await page.locator('#place-done').click();if((await state()).placements.home.length!==1)throw new Error('겹친 자리에 배치됨');await page.locator('#rotate-button').click();await page.locator('#rotate-button').click();
await clickWorld(204,250);await page.locator('#place-done').click();
console.log('furniture',JSON.stringify((await state()).placements.home));
await clickNode('berry1');await clickNode('berry2');
await page.locator('[data-panel="friends"]').click();await page.locator('[data-action="conditions"]').click();await page.locator('[data-invite="kong"]').click();await page.evaluate(()=>window.advanceTime(21000));
await page.locator('[data-chick="kong"]').click();await page.locator('[data-action="settle"]').click();
console.log('resident',JSON.stringify({residents:(await state()).residents,rep:(await state()).rep}));
const positions=[];for(let i=0;i<5;i++){positions.push(await page.locator('[data-chick="kong"] image').getAttribute('x'));await page.evaluate(()=>window.advanceTime(4000))}if(new Set(positions).size<2)throw new Error('친구가 자율 이동하지 않음');
await page.locator('[data-object]').first().click();await page.locator('[data-action="start-play"]').click();for(let i=0;i<4;i++)await page.locator('[data-action="push"]').click();
console.log('played',JSON.stringify({memories:(await state()).memories,rep:(await state()).rep}));
await page.screenshot({path:'output/web-game/v2-progress.png'});
await page.locator('#sheet-close').click();
await page.evaluate(()=>window.advanceTime(151000));await clickNode('wood1');await clickNode('wood2');await clickNode('stone1');
await page.locator('[data-panel="craft"]').click();await page.locator('[data-craft="axe"]').click();await page.evaluate(()=>window.advanceTime(11000));await page.locator('#sheet-close').click();
await page.locator('[data-gate="forest"]').click();await page.locator('[data-unlock="forest"]').click();
console.log('forest',JSON.stringify({region:(await state()).region,unlocked:(await state()).unlocked,tools:(await state()).tools}));
await clickNode('wood1');await clickNode('wood2');await clickNode('stone1');
await page.locator('[data-panel="craft"]').click();await page.locator('[data-craft="farm"]').click();await page.evaluate(()=>window.advanceTime(11000));await page.locator('#sheet-close').click();await page.locator('[data-panel="storage"]').click();await page.locator('[data-place="farm"]').click();
await clickWorld(195,372);await page.locator('#place-done').click();
console.log('forest furniture',JSON.stringify((await state()).placements.forest));
await page.locator('[data-object]').first().click();await page.locator('[data-action="farm"]').click();await page.evaluate(()=>window.advanceTime(481000));await page.locator('[data-action="farm"]').click();
console.log('harvest',JSON.stringify({carrot:(await state()).inventory.carrot,farms:(await page.evaluate(()=>window.__chickGame.getState())).farms}));
await page.screenshot({path:'output/web-game/v2-forest.png'});
await page.reload();console.log('reload',JSON.stringify({region:(await state()).region,carrot:(await state()).inventory.carrot,placements:(await state()).placements.forest.length}));
await clickNode('wood1');await clickNode('wood2');await clickNode('stone1');
await page.locator('#region-button').click();await page.locator('[data-region="home"]').click();
await clickNode('wood1');await clickNode('wood2');await clickNode('stone1');await page.evaluate(()=>window.advanceTime(151000));await clickNode('stone1');
await page.locator('[data-panel="craft"]').click();await page.locator('[data-craft="stove"]').click();await page.evaluate(()=>window.advanceTime(21000));await page.locator('[data-craft="table"]').click();await page.evaluate(()=>window.advanceTime(11000));await page.locator('#sheet-close').click();
await page.locator('[data-panel="storage"]').click();await page.locator('[data-place="stove"]').click();await clickWorld(110,357);await page.locator('#place-done').click();
await page.locator('[data-panel="storage"]').click();await page.locator('[data-place="table"]').click();await clickWorld(260,312);await page.locator('#place-done').click();
console.log('kitchen',JSON.stringify((await state()).placements.home));
await clickNode('berry1');await page.locator('[data-object="p4"]').click();await page.locator('[data-cook="tea"]').click();await page.evaluate(()=>window.advanceTime(31000));await page.locator('[data-action="collect-cook"]').click();await page.locator('#sheet-close').click();
await page.locator('[data-panel="friends"]').click();await page.locator('[data-action="conditions"]').click();await page.locator('[data-invite="tori"]').click();await page.evaluate(()=>window.advanceTime(21000));await page.locator('[data-chick="tori"]').click();await page.locator('[data-action="settle"]').click();
console.log('tori',JSON.stringify({residents:(await state()).residents,rep:(await state()).rep,tea:(await state()).inventory.tea}));
await page.screenshot({path:'output/web-game/v2-tori.png'});
await page.locator('#region-button').click();await page.locator('[data-region="forest"]').click();await clickNode('herb1');
await page.locator('[data-panel="friends"]').click();await page.locator('[data-friend="tori"]').click();await page.locator('[data-story="tori"]').click();
console.log('story',JSON.stringify({rep:(await state()).rep,stories:(await page.evaluate(()=>window.__chickGame.getState())).stories}));await page.locator('#sheet-close').click();
await page.locator('#region-button').click();await page.locator('[data-region="home"]').click();await page.evaluate(()=>window.advanceTime(151000));await clickNode('wood1');await clickNode('wood2');await clickNode('stone1');await page.evaluate(()=>window.advanceTime(151000));await clickNode('stone1');
await page.locator('[data-gate="river"]').click();await page.locator('[data-unlock="river"]').click();
console.log('river',JSON.stringify({region:(await state()).region,rep:(await state()).rep,unlocked:(await state()).unlocked}));
await page.locator('[data-panel="storage"]').click();await page.locator('[data-move="p2"]').click();await page.locator('#place-done').click();
console.log('moved',JSON.stringify({home:(await state()).placements.home.map(o=>o.id),river:(await state()).placements.river.map(o=>o.id)}));
await page.screenshot({path:'output/web-game/v2-river.png'});
await clickNode('stone1');await clickNode('stone2');await page.locator('#region-button').click();await page.locator('[data-region="forest"]').click();await clickNode('wood1');await clickNode('wood2');await clickNode('stone1');
await page.locator('#region-button').click();await page.locator('[data-region="home"]').click();await clickNode('wood1');await clickNode('wood2');
await page.locator('[data-panel="craft"]').click();await page.locator('[data-craft="pickaxe"]').click();await page.evaluate(()=>window.advanceTime(21000));await page.locator('#sheet-close').click();
await page.locator('#region-button').click();await page.locator('[data-region="forest"]').click();await page.locator('[data-gate="ridge"]').click();await page.locator('[data-unlock="ridge"]').click();await clickNode('ore1');
console.log('ridge',JSON.stringify({region:(await state()).region,ore:(await state()).inventory.ore,tools:(await state()).tools}));
await page.screenshot({path:'output/web-game/v2-ridge.png'});
console.log('errors',JSON.stringify(errors));
await browser.close();
